/**
 * Original crisis catalog for the Dead of Winter base pack.
 *
 * The ids remain the long-lived `cr-1` through `cr-20` identifiers used by
 * saved games and engine regressions. The names, copy, symbol mix, and
 * consequences are authored for this pack rather than transcribed from a
 * retail card set.
 */

import type { CrisisCardDefinition } from '../schema.js';

export const BASE_CRISES: CrisisCardDefinition[] = [
  {
    id: 'cr-1',
    name: 'Armory Door Jam',
    text: 'The armory is frozen shut. Contribute weapons to force it open before the next patrol.',
    acceptedSymbols: ['weapon'],
    failure: { kind: 'adjustMorale', amount: -2 },
    overContribution: {
      text: 'The cleared armory yields one food crate for the colony stores.',
      effect: { kind: 'adjustFood', amount: 1 },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'cr-2',
    name: 'Dead Generator Line',
    text: 'The colony lights are failing. Contribute fuel to restart the buried generator.',
    acceptedSymbols: ['fuel'],
    failure: { kind: 'addZombies', count: 2, location: { kind: 'colony' } },
    overContribution: {
      text: 'A clean restart keeps one extra food shipment from spoiling.',
      effect: { kind: 'adjustFood', amount: 1 },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'cr-3',
    name: 'Torn Perimeter Map',
    text: 'The perimeter map is in pieces. Contribute tools or education cards to rebuild a safe route.',
    acceptedSymbols: ['tool', 'education'],
    failure: { kind: 'addNoise', count: 2, location: { kind: 'colony' } },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'cr-4',
    name: 'Empty Treatment Cart',
    text: 'The infirmary cart is bare. Contribute medicine or food to keep the night ward open.',
    acceptedSymbols: ['medicine', 'food'],
    failure: { kind: 'adjustMorale', amount: -1 },
    overContribution: {
      text: 'The surplus lets the medic tend the least-influential survivor at the colony, if able.',
      effect: {
        kind: 'ifAble',
        effect: {
          kind: 'heal',
          amount: 1,
          target: { kind: 'lowestInfluenceAt', location: { kind: 'colony' } },
        },
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'cr-5',
    name: 'Schoolhouse Signal',
    text: 'A signal lamp is visible at the school. Contribute education cards to decode its pattern.',
    acceptedSymbols: ['education'],
    failure: { kind: 'addZombies', count: 1, location: { kind: 'fixed', location: 'school' } },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'cr-6',
    name: 'Fuel Siphon Leak',
    text: 'A leak is draining the reserve tank. Contribute fuel or tools to seal the line.',
    acceptedSymbols: ['fuel', 'tool'],
    failure: { kind: 'adjustFood', amount: -1 },
    overContribution: {
      text: 'A careful repair saves enough fuel to add one food to the stores.',
      effect: { kind: 'adjustFood', amount: 1 },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'cr-7',
    name: 'Quiet Ward Shortage',
    text: 'The hospital needs medicine and a steady hand. Contribute medicine or survivor cards to staff it.',
    acceptedSymbols: ['medicine', 'survivor'],
    failure: { kind: 'adjustMorale', amount: -2 },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'cr-8',
    name: 'Grocery Loading Bay',
    text: 'A delivery truck is trapped behind the grocery loading bay. Contribute tools or fuel to free it.',
    acceptedSymbols: ['tool', 'fuel'],
    failure: { kind: 'addZombies', count: 1, location: { kind: 'fixed', location: 'grocery-store' } },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'cr-9',
    name: 'Library Boiler Notes',
    text: 'The library boiler can be restarted, but its instructions are incomplete. Contribute education cards.',
    acceptedSymbols: ['education'],
    failure: { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'library' } },
    overContribution: {
      text: 'The extra notes reveal a hidden pantry: add one food to the colony stores.',
      effect: { kind: 'adjustFood', amount: 1 },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'cr-10',
    name: 'Barricade Hardware Run',
    text: 'The colony needs hardware before dusk. Contribute tools or weapons to reinforce the gates.',
    acceptedSymbols: ['tool', 'weapon'],
    failure: { kind: 'addZombies', count: 2, location: { kind: 'colony' } },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'cr-11',
    name: 'Missing Meal Ledger',
    text: 'The meal ledger has vanished. Contribute food or education cards to reconcile the ration count.',
    acceptedSymbols: ['food', 'education'],
    failure: { kind: 'addStarvation', amount: 1 },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'cr-12',
    name: 'Roadside Triage',
    text: 'A stranded group is approaching the colony. Contribute medicine or food before admitting them.',
    acceptedSymbols: ['medicine', 'food'],
    failure: { kind: 'adjustMorale', amount: -1 },
    overContribution: {
      text: 'The group leaves one helpless survivor at the colony.',
      effect: { kind: 'addHelpless', count: 1 },
    },
    nonCooperative: false,
    matureContent: true,
  },
  {
    id: 'cr-13',
    name: 'Frozen Fleet',
    text: 'The colony vehicles are iced in. Contribute fuel or tools to make one route passable.',
    acceptedSymbols: ['fuel', 'tool'],
    failure: { kind: 'adjustRounds', amount: -1 },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'cr-14',
    name: 'Watchtower Roster',
    text: 'The watchtower roster is out of date. Contribute survivor or education cards to organize the watch.',
    acceptedSymbols: ['survivor', 'education'],
    failure: { kind: 'addNoise', count: 2, location: { kind: 'colony' } },
    nonCooperative: true,
    matureContent: false,
  },
  {
    id: 'cr-15',
    name: 'Emergency Water Melt',
    text: 'The water barrels are frozen solid. Contribute fuel or food to melt enough for the next ration.',
    acceptedSymbols: ['fuel', 'food'],
    failure: { kind: 'addStarvation', amount: 1 },
    overContribution: {
      text: 'A full melt leaves one food crate ready for distribution.',
      effect: { kind: 'adjustFood', amount: 1 },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'cr-16',
    name: 'Clinic Door Brace',
    text: 'The clinic door will not hold. Contribute tools or weapons to brace it against the night.',
    acceptedSymbols: ['tool', 'weapon'],
    failure: { kind: 'addZombies', count: 1, location: { kind: 'fixed', location: 'hospital' } },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'cr-17',
    name: 'Radio Relay Battery',
    text: 'The radio relay is almost silent. Contribute fuel or education cards to bring the signal back.',
    acceptedSymbols: ['fuel', 'education'],
    failure: { kind: 'adjustMorale', amount: -1 },
    nonCooperative: true,
    matureContent: false,
  },
  {
    id: 'cr-18',
    name: 'The Long Night Shift',
    text: 'The watch has gone too long without rest. Contribute survivor or medicine cards to rotate the shift.',
    acceptedSymbols: ['survivor', 'medicine'],
    failure: { kind: 'adjustMorale', amount: -2 },
    nonCooperative: false,
    matureContent: true,
  },
  {
    id: 'cr-19',
    name: 'Canteen Inventory',
    text: 'The canteen inventory is wrong. Contribute food or tools to count every sealed container.',
    acceptedSymbols: ['food', 'tool'],
    failure: { kind: 'adjustFood', amount: -2 },
    overContribution: {
      text: 'The count uncovers one extra food ration for the stores.',
      effect: { kind: 'adjustFood', amount: 1 },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'cr-20',
    name: 'Last Safe Crossing',
    text: 'The safest crossing will disappear under the snow. Contribute weapons, fuel, or tools to mark it.',
    acceptedSymbols: ['weapon', 'fuel', 'tool'],
    failure: { kind: 'addZombies', count: 1, location: { kind: 'colony' } },
    nonCooperative: false,
    matureContent: false,
  },
];
