/**
 * Original crossroads catalog for the Dead of Winter base pack.
 *
 * The `xr-*` identifiers are stable save-game identifiers. Four named cards
 * retain their established definitions because §18 regression tests rely on
 * their exact trigger and option semantics; every other entry replaces inert
 * content with a distinct, executable choice.
 */

import type { CrossroadsCardDefinition } from '../schema.js';

export const BASE_CROSSROADS: CrossroadsCardDefinition[] = [
  {
    id: 'xr-move-test',
    name: 'Something in the Snow',
    story: 'A shape moves between the drifts.',
    trigger: { event: 'moveCompleted', destination: 'any' },
    options: [
      { id: 'ignore', text: 'Keep walking.', outcome: { kind: 'adjustMorale', amount: -1 } },
      {
        id: 'investigate',
        text: 'Investigate — only if the colony still has food.',
        requires: { kind: 'food', atLeast: 1 },
        outcome: { kind: 'adjustFood', amount: -1 },
      },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-old-divisions',
    name: 'Old Divisions',
    story: 'The helpless are a burden, someone says. Loudly.',
    // §18.1 errata: triggers only if a survivor controlled by the active player
    // is at the colony AND at least one helpless survivor is at the colony.
    trigger: {
      event: 'turnStart',
      requires: {
        kind: 'all',
        of: [
          {
            kind: 'survivorsAt',
            location: { kind: 'colony' },
            controlledBy: { kind: 'activePlayer' },
            atLeast: 1,
          },
          { kind: 'helplessSurvivors', atLeast: 1 },
        ],
      },
    },
    options: [
      {
        id: 'thumbs-up',
        text: 'Thumbs up — the contributions are withdrawn unseen.',
        // §18.4: remove existing crisis contributions *without revealing them*.
        outcome: { kind: 'removeCrisisContributions', reveal: false },
      },
      { id: 'thumbs-down', text: 'Thumbs down.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-outbreak',
    name: 'Outbreak',
    story: 'Something is wrong inside the walls.',
    trigger: { event: 'turnStart' },
    // §15/§18.4: voted on only by players with at least one survivor at the
    // colony. The electorate is expressed on the vote effect, not on the card —
    // the card carries no `chooser`, because a vote is not a chooser.
    options: [
      {
        id: 'quarantine',
        text: 'Quarantine.',
        outcome: {
          kind: 'vote',
          prompt: 'Quarantine the sick?',
          electorate: 'colonySurvivors',
          onPass: { kind: 'adjustMorale', amount: -1 },
          onFail: { kind: 'addZombies', count: 1, location: { kind: 'colony' } },
        },
      },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-this-taste-funny',
    name: 'This Taste Funny',
    story: 'The stew is... fine. Probably.',
    // §18.4: the player holding/drawing the card is not intended to trigger it
    // themselves. Since §10 already scopes every trigger to the active player
    // and the holder is the player on their right, that is structural here.
    trigger: { event: 'actionPerformed', action: 'search' },
    options: [
      { id: 'eat', text: 'Eat it anyway.', outcome: { kind: 'adjustFood', amount: 1 } },
      { id: 'refuse', text: 'Refuse.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-mature-sample',
    name: 'A Grim Discovery',
    story: 'The hospital team finds a blood-marked coat beneath the ward stairs.',
    trigger: { event: 'survivorKilled' },
    options: [
      {
        id: 'seal-ward',
        text: 'Seal the ward and clear one zombie from the hospital, if able.',
        requires: { kind: 'zombiesAt', location: { kind: 'fixed', location: 'hospital' }, atLeast: 1 },
        outcome: {
          kind: 'removeZombies',
          count: 1,
          location: { kind: 'fixed', location: 'hospital' },
        },
      },
      {
        id: 'tell-colony',
        text: 'Tell everyone what was found; morale falls by one.',
        outcome: { kind: 'adjustMorale', amount: -1 },
      },
    ],
    matureContent: true,
    nonCooperative: false,
  },
  {
    id: 'xr-exile-dependent',
    name: 'Voices Outside',
    story: 'Someone is shouting from beyond the fence, using a name the colony remembers.',
    trigger: { event: 'turnStart', requires: { kind: 'playerExiled', player: { kind: 'activePlayer' } } },
    options: [
      {
        id: 'answer',
        text: 'Answer the voice and spend one food, if the colony has any.',
        requires: { kind: 'food', atLeast: 1 },
        outcome: { kind: 'adjustFood', amount: -1 },
      },
      {
        id: 'reinforce',
        text: 'Reinforce the colony gate and add one noise there.',
        outcome: {
          kind: 'sequence',
          effects: [
            { kind: 'addBarricade', count: 1, location: { kind: 'colony' } },
            { kind: 'addNoise', count: 1, location: { kind: 'colony' } },
          ],
        },
      },
    ],
    matureContent: false,
    nonCooperative: true,
    // §19.6's third suggestion removes exile-dependent content.
    dependsOnExile: true,
  },
  {
    id: 'xr-impossible',
    name: 'No Way Out',
    story: 'The only clear route is blocked by a drift, but the colony can still choose how to spend the hour.',
    trigger: { event: 'actionPerformed', action: 'move' },
    options: [
      {
        id: 'push-on',
        text: 'Push through the drift and place a barricade at the colony, if someone is home.',
        requires: { kind: 'survivorsAt', location: { kind: 'colony' }, atLeast: 1 },
        outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } },
      },
      {
        id: 'wait-out',
        text: 'Wait for the storm; morale falls by one.',
        outcome: { kind: 'adjustMorale', amount: -1 },
      },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f1',
    name: 'Lantern at the Gate',
    story: 'A lantern swings from the gatehouse, though no watch volunteer claims to have lit it.',
    trigger: { event: 'turnStart' },
    options: [
      {
        id: 'steady-lantern',
        text: 'Steady the lantern and place one barricade at the colony.',
        outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } },
      },
      { id: 'save-oil', text: 'Save the oil and lose one food from the stores.', outcome: { kind: 'adjustFood', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f2',
    name: 'Names on the Wall',
    story: 'Fresh names have been scratched into the colony wall beneath the old roll call.',
    trigger: { event: 'turnStart' },
    options: [
      {
        id: 'read-aloud',
        text: 'Read the names aloud and raise morale by one, if morale is five or lower.',
        requires: { kind: 'morale', atMost: 5 },
        outcome: { kind: 'adjustMorale', amount: 1 },
      },
      { id: 'paint-over', text: 'Paint over the wall and add one noise at the colony.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f3',
    name: 'Gatehouse Rattle',
    story: 'The gatehouse rattles in a windless hour, and a single muddy handprint appears outside.',
    trigger: { event: 'turnStart' },
    options: [
      {
        id: 'check-hinge',
        text: 'Check the hinge and remove one colony zombie, if able.',
        requires: { kind: 'zombiesAt', location: { kind: 'colony' }, atLeast: 1 },
        outcome: { kind: 'removeZombies', count: 1, location: { kind: 'colony' } },
      },
      { id: 'bar-door', text: 'Bar the door and add one barricade at the colony.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f4',
    name: 'The Shared Blanket',
    story: 'A child-sized blanket is passed from bunk to bunk until nobody remembers who brought it in.',
    trigger: { event: 'turnStart' },
    options: [
      {
        id: 'share-ration',
        text: 'Share the next meal: spend one food and gain one morale.',
        requires: { kind: 'food', atLeast: 1 },
        outcome: { kind: 'sequence', effects: [{ kind: 'adjustFood', amount: -1 }, { kind: 'adjustMorale', amount: 1 }] },
      },
      { id: 'keep-warm', text: 'Keep the stores sealed and add two noise at the colony.', outcome: { kind: 'addNoise', count: 2, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f5',
    name: 'Snowbound Calendar',
    story: 'The calendar has frozen to the wall, marking a day that feels farther away than the last.',
    trigger: { event: 'turnStart' },
    options: [
      { id: 'mark-day', text: 'Mark another day survived and add one round to the clock.', outcome: { kind: 'adjustRounds', amount: 1 } },
      { id: 'count-supplies', text: 'Count the stores instead and add one starvation token.', outcome: { kind: 'addStarvation', amount: 1 } },
    ],
    matureContent: true,
    nonCooperative: false,
  },
  {
    id: 'xr-f6',
    name: 'Late Watch Whistle',
    story: 'A whistle sounds after the late watch should have come inside.',
    trigger: { event: 'turnStart' },
    options: [
      { id: 'answer-whistle', text: 'Answer the whistle and add one noise at the colony.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'colony' } } },
      { id: 'hold-silence', text: 'Hold the silence and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f7',
    name: 'Ration Chalk Marks',
    story: 'Someone has drawn a second set of ration marks beneath the official count.',
    trigger: { event: 'turnStart' },
    options: [
      {
        id: 'recount',
        text: 'Recount the stores, spending one food to raise morale by one.',
        requires: { kind: 'food', atLeast: 1 },
        outcome: { kind: 'sequence', effects: [{ kind: 'adjustFood', amount: -1 }, { kind: 'adjustMorale', amount: 1 }] },
      },
      { id: 'lock-ledger', text: 'Lock the ledger and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f8',
    name: 'Frost on the Barricade',
    story: 'Rime has sealed the knots in the outer barricade, making every repair a noisy one.',
    trigger: { event: 'turnStart' },
    options: [
      {
        id: 'scrape-frost',
        text: 'Scrape the frost away and remove one colony noise, if able.',
        outcome: {
          kind: 'ifAble',
          effect: { kind: 'removeNoise', count: 1, location: { kind: 'colony' } },
        },
      },
      { id: 'leave-it', text: 'Leave the frost in place and add one barricade at the colony.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f9',
    name: 'The Last Shift Change',
    story: 'The shift bell rings at the end of the day, but the names on the board are all crossed out.',
    trigger: { event: 'turnEnd' },
    options: [
      { id: 'ring-back', text: 'Ring the bell back and add one morale.', outcome: { kind: 'adjustMorale', amount: 1 } },
      { id: 'close-gate', text: 'Close the gate early and add one noise at the colony.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f10',
    name: 'Boot Prints Indoors',
    story: 'Wet boot prints cross the colony floor and stop beside the empty chair at the end of the table.',
    trigger: { event: 'turnEnd' },
    options: [
      { id: 'follow-trail', text: 'Follow the trail and add one barricade at the colony.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
      { id: 'mop-floor', text: 'Mop it up and spend one food on a late meal, if able.', requires: { kind: 'food', atLeast: 1 }, outcome: { kind: 'adjustFood', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f11',
    name: 'Kitchen Window Glow',
    story: 'The kitchen window glows after the lamps have been turned down for the night.',
    trigger: { event: 'turnEnd' },
    options: [
      { id: 'check-kitchen', text: 'Check the kitchen and add one food to the stores.', outcome: { kind: 'adjustFood', amount: 1 } },
      { id: 'darken-window', text: 'Darken the window and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f12',
    name: 'Red Scarf on the Fence',
    story: 'A red scarf is tied to the fence, its knot fresh despite the falling snow.',
    trigger: { event: 'turnEnd' },
    options: [
      { id: 'bring-scarf-in', text: 'Bring the scarf inside and add one noise at the colony.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'colony' } } },
      { id: 'leave-marker', text: 'Leave the marker and add one barricade at the colony.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f13',
    name: 'Unclaimed Bunk',
    story: 'An unclaimed bunk has been made neatly, with a folded coat at its foot.',
    trigger: { event: 'turnEnd' },
    options: [
      { id: 'reserve-bunk', text: 'Reserve the bunk and raise morale by one.', outcome: { kind: 'adjustMorale', amount: 1 } },
      { id: 'use-bunk', text: 'Use the space for supplies and add one food to the stores.', outcome: { kind: 'adjustFood', amount: 1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f14',
    name: 'The Locked Pantry',
    story: 'A pantry lock has been replaced with a key nobody recognizes.',
    trigger: { event: 'turnEnd' },
    options: [
      { id: 'break-lock', text: 'Break the lock and add one food to the stores.', outcome: { kind: 'adjustFood', amount: 1 } },
      { id: 'respect-lock', text: 'Respect the lock and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: true,
  },
  {
    id: 'xr-f15',
    name: 'A Voice on the Radio',
    story: 'A radio voice counts down from ten, then asks who is still listening.',
    trigger: { event: 'turnEnd' },
    options: [
      { id: 'reply', text: 'Reply with the colony call sign and raise morale by one.', outcome: { kind: 'adjustMorale', amount: 1 } },
      { id: 'cut-power', text: 'Cut the power and add one noise at the colony.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f16',
    name: 'The Empty Shelf',
    story: 'A search turns up an empty shelf where a supply ledger says a full crate should be.',
    trigger: { event: 'actionPerformed', action: 'search' },
    options: [
      { id: 'record-loss', text: 'Record the loss and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
      { id: 'search-again', text: 'Search the room again and add one noise at the colony.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f17',
    name: 'Axe Marks at the Door',
    story: 'Fresh axe marks circle a door that was locked from the inside.',
    trigger: { event: 'actionPerformed', action: 'attackZombie' },
    options: [
      {
        id: 'clear-threshold',
        text: 'Use the opening to remove one zombie at the colony, if able.',
        requires: { kind: 'zombiesAt', location: { kind: 'colony' }, atLeast: 1 },
        outcome: { kind: 'removeZombies', count: 1, location: { kind: 'colony' } },
      },
      { id: 'guard-door', text: 'Guard the door and add one barricade at the colony.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: true,
    nonCooperative: false,
  },
  {
    id: 'xr-f18',
    name: 'The Bent Hinge',
    story: 'A gate hinge bends after the fighting, leaving a gap just wide enough for a hand.',
    trigger: { event: 'actionPerformed', action: 'barricade' },
    options: [
      { id: 'replace-hinge', text: 'Replace the hinge and raise morale by one.', outcome: { kind: 'adjustMorale', amount: 1 } },
      { id: 'wedge-door', text: 'Wedge the door and add one noise at the colony.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f19',
    name: 'Soup for the Watch',
    story: 'The watch has left a pot simmering, though the kitchen roster has no cook assigned.',
    trigger: { event: 'actionPerformed', action: 'cleanWaste' },
    options: [
      { id: 'serve-soup', text: 'Serve the soup and add one food to the stores.', outcome: { kind: 'adjustFood', amount: 1 } },
      { id: 'save-soup', text: 'Save it for morning and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f20',
    name: 'The Echoing Yard',
    story: 'A call from the yard comes back as three echoes, each from a different direction.',
    trigger: { event: 'actionPerformed', action: 'attract' },
    options: [
      { id: 'draw-away', text: 'Draw the echoes away and remove one noise at the colony, if able.', outcome: { kind: 'ifAble', effect: { kind: 'removeNoise', count: 1, location: { kind: 'colony' } } } },
      { id: 'let-echoes', text: 'Let the echoes fade and add one barricade at the colony.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f21',
    name: 'A Choice of Bandages',
    story: 'Two sealed bandage rolls sit on a hospital cart, one marked for the colony and one for nobody.',
    trigger: { event: 'actionPerformed', action: 'ability' },
    options: [
      {
        id: 'treat-wounded',
        text: 'Treat the least-influential survivor at the colony, if one is there.',
        requires: { kind: 'survivorsAt', location: { kind: 'colony' }, atLeast: 1 },
        outcome: { kind: 'heal', amount: 1, target: { kind: 'lowestInfluenceAt', location: { kind: 'colony' } } },
      },
      { id: 'save-rolls', text: 'Save the bandages and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: true,
    nonCooperative: false,
  },
  {
    id: 'xr-f22',
    name: 'The Borrowed Coat',
    story: 'A borrowed coat returns to the rack with a fresh patch sewn over its missing pocket.',
    trigger: { event: 'actionPerformed', action: 'playItem' },
    options: [
      { id: 'thank-tailor', text: 'Thank the tailor and raise morale by one.', outcome: { kind: 'adjustMorale', amount: 1 } },
      { id: 'check-pocket', text: 'Check the pocket and add one noise at the colony.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f23',
    name: 'The Unspent Token',
    story: 'A food token is found beneath a table, scratched with a date from before the snow.',
    trigger: { event: 'actionPerformed', action: 'playFoodForDie' },
    options: [
      { id: 'honor-token', text: 'Honor the old ration and spend one food from the stores.', outcome: { kind: 'adjustFood', amount: -1 } },
      { id: 'break-token', text: 'Break the token for luck and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f24',
    name: 'Colony Arrival',
    story: 'A survivor reaches the colony gate just as the last light leaves the sky.',
    trigger: { event: 'moveCompleted', destination: 'colony' },
    options: [
      { id: 'welcome-arrival', text: 'Welcome the arrival and place one barricade at the colony.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
      { id: 'share-news', text: 'Share the news with the watch and raise morale by one.', outcome: { kind: 'adjustMorale', amount: 1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f25',
    name: 'The Hospital Return',
    story: 'A survivor returning from the hospital carries a list of names no one wants to read.',
    trigger: { event: 'moveCompleted', destination: 'nonColony' },
    options: [
      { id: 'read-list', text: 'Read the list and remove one hospital noise, if able.', outcome: { kind: 'ifAble', effect: { kind: 'removeNoise', count: 1, location: { kind: 'fixed', location: 'hospital' } } } },
      { id: 'fold-list', text: 'Fold the list away and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f26',
    name: 'Wrong Turn at School',
    story: 'Tracks from the school end at a classroom window, although the door was never opened.',
    trigger: { event: 'moveCompleted', destination: 'any' },
    options: [
      { id: 'mark-window', text: 'Mark the window and add one school noise.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'school' } } },
      { id: 'leave-school', text: 'Leave the school alone and add one food to the stores.', outcome: { kind: 'adjustFood', amount: 1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f27',
    name: 'A Warm Hospital Bed',
    story: 'One hospital bed is warm, though the room has been empty since dawn.',
    trigger: { event: 'moveCompleted', destination: 'nonColony' },
    options: [
      { id: 'use-bed', text: 'Use the bed for the least-influential colony survivor, if one is there.', requires: { kind: 'survivorsAt', location: { kind: 'colony' }, atLeast: 1 }, outcome: { kind: 'heal', amount: 1, target: { kind: 'lowestInfluenceAt', location: { kind: 'colony' } } } },
      { id: 'save-bed', text: 'Save the bed for later and raise morale by one.', outcome: { kind: 'adjustMorale', amount: 1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f28',
    name: 'Gas Station Detour',
    story: 'A detour past the gas station reveals a pump handle still ticking in the cold.',
    trigger: { event: 'moveCompleted', destination: 'nonColony' },
    options: [
      { id: 'check-pump', text: 'Check the pump and remove one gas-station zombie, if able.', requires: { kind: 'zombiesAt', location: { kind: 'fixed', location: 'gas-station' }, atLeast: 1 }, outcome: { kind: 'removeZombies', count: 1, location: { kind: 'fixed', location: 'gas-station' } } },
      { id: 'avoid-pump', text: 'Avoid the pump and add one gas-station noise.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'gas-station' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f29',
    name: 'Library Door Open',
    story: 'The library door stands open after a journey that should have ended at the colony.',
    trigger: { event: 'moveCompleted', destination: 'any' },
    options: [
      { id: 'close-library', text: 'Close the library door and remove one colony noise, if able.', outcome: { kind: 'ifAble', effect: { kind: 'removeNoise', count: 1, location: { kind: 'colony' } } } },
      { id: 'leave-door', text: 'Leave it open as a marker and add one library noise.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'library' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f30',
    name: 'A Place at the Table',
    story: 'A place is set at the colony table for someone who has not returned from the last trip.',
    trigger: { event: 'moveCompleted', destination: 'colony' },
    options: [
      { id: 'set-another-place', text: 'Set another place and add one helpless survivor, if able.', outcome: { kind: 'ifAble', effect: { kind: 'addHelpless', count: 1 } } },
      { id: 'clear-table', text: 'Clear the table and spend one food on the living, if able.', requires: { kind: 'food', atLeast: 1 }, outcome: { kind: 'adjustFood', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f31',
    name: 'A Quiet Kill',
    story: 'The last zombie falls without a sound, leaving the yard quieter than it was before.',
    trigger: { event: 'zombieKilled' },
    options: [
      { id: 'use-quiet', text: 'Use the quiet to remove one colony noise, if able.', outcome: { kind: 'ifAble', effect: { kind: 'removeNoise', count: 1, location: { kind: 'colony' } } } },
      { id: 'signal-watch', text: 'Signal the watch and place one barricade at the colony.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f32',
    name: 'The Cleared Stairwell',
    story: 'The stairwell is clear for the first time in days, and footsteps carry all the way to the roof.',
    trigger: { event: 'zombieKilled' },
    options: [
      { id: 'claim-stairwell', text: 'Claim the stairwell and raise morale by one.', outcome: { kind: 'adjustMorale', amount: 1 } },
      { id: 'restock-stairwell', text: 'Use it as a store route and spend one food on the crew, if able.', requires: { kind: 'food', atLeast: 1 }, outcome: { kind: 'adjustFood', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f33',
    name: 'The Hospital Exhale',
    story: 'After the fight, the hospital seems to exhale through every cracked pane of glass.',
    trigger: { event: 'zombieKilled' },
    options: [
      { id: 'tend-wounds', text: 'Tend the least-influential survivor at the hospital, if one is there.', requires: { kind: 'survivorsAt', location: { kind: 'fixed', location: 'hospital' }, atLeast: 1 }, outcome: { kind: 'heal', amount: 1, target: { kind: 'lowestInfluenceAt', location: { kind: 'fixed', location: 'hospital' } } } },
      { id: 'open-windows', text: 'Open the windows and add one hospital noise.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'hospital' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f34',
    name: 'Broken Watch Strap',
    story: 'A broken watch strap is found beside the place where a sentry made the final call.',
    trigger: { event: 'zombieKilled' },
    options: [
      { id: 'honor-sentry', text: 'Honor the sentry and remove one colony barricade, if one stands.', requires: { kind: 'barricadesAt', location: { kind: 'colony' }, atLeast: 1 }, outcome: { kind: 'removeBarricade', count: 1, location: { kind: 'colony' } } },
      { id: 'replace-strap', text: 'Replace the strap and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: true,
    nonCooperative: false,
  },
  {
    id: 'xr-f35',
    name: 'A Bite of Good News',
    story: 'A scavenger reports a quiet route, then admits the route ends at a locked grocery door.',
    trigger: { event: 'zombieKilled' },
    options: [
      { id: 'trust-report', text: 'Trust the report and add one zombie to the grocery store.', outcome: { kind: 'addZombies', count: 1, location: { kind: 'fixed', location: 'grocery-store' } } },
      { id: 'keep-hope', text: 'Keep the good news and add one food to the stores.', outcome: { kind: 'adjustFood', amount: 1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f36',
    name: 'Plywood Victory',
    story: 'The crew raises a scrap of plywood like a flag after securing the school entrance.',
    trigger: { event: 'zombieKilled' },
    options: [
      { id: 'raise-flag', text: 'Raise the flag and place one school barricade.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'fixed', location: 'school' } } },
      { id: 'lower-flag', text: 'Lower the flag and add one school noise.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'school' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f37',
    name: 'The Exiled Signal',
    story: 'A signal from beyond the perimeter answers the colony radio with a phrase only an exile would know.',
    trigger: { event: 'zombieKilled', requires: { kind: 'playerExiled', player: { kind: 'activePlayer' } } },
    options: [
      { id: 'answer-signal', text: 'Answer the signal and spend one food, if the colony has any.', requires: { kind: 'food', atLeast: 1 }, outcome: { kind: 'adjustFood', amount: -1 } },
      { id: 'jam-signal', text: 'Jam the signal and add one noise at the colony.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: true,
    dependsOnExile: true,
  },
  {
    id: 'xr-f38',
    name: 'Winter Takes Its Due',
    story: 'The cold settles over the cleared streets, asking whether one victory can pay for the next night.',
    trigger: { event: 'zombieKilled' },
    options: [
      { id: 'keep-moving', text: 'Keep moving and add one round to the clock.', outcome: { kind: 'adjustRounds', amount: 1 } },
      { id: 'hold-ground', text: 'Hold the ground and add one starvation token.', outcome: { kind: 'addStarvation', amount: 1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f39',
    name: 'The Empty Coat Hook',
    story: 'A coat hook swings after the room has emptied, tapping the wall at a steady pace.',
    trigger: { event: 'survivorKilled' },
    options: [
      { id: 'hang-coat', text: 'Hang a spare coat and add one helpless survivor, if able.', outcome: { kind: 'ifAble', effect: { kind: 'addHelpless', count: 1 } } },
      { id: 'clear-hook', text: 'Clear the hook and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: true,
    nonCooperative: false,
  },
  {
    id: 'xr-f40',
    name: 'A Seat Gone Cold',
    story: 'A seat at the colony table goes cold before anyone has finished setting out the bowls.',
    trigger: { event: 'survivorKilled' },
    options: [
      { id: 'finish-meal', text: 'Finish the meal and add one food to the stores.', outcome: { kind: 'adjustFood', amount: 1 } },
      { id: 'empty-bowl', text: 'Leave the bowl in place and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: true,
  },
  {
    id: 'xr-f41',
    name: 'The Unused Splint',
    story: 'A splint remains tied to a hospital bed after its patient is carried elsewhere.',
    trigger: { event: 'survivorKilled' },
    options: [
      { id: 'reuse-splint', text: 'Reuse the splint on the least-influential hospital survivor, if one is there.', requires: { kind: 'survivorsAt', location: { kind: 'fixed', location: 'hospital' }, atLeast: 1 }, outcome: { kind: 'heal', amount: 1, target: { kind: 'lowestInfluenceAt', location: { kind: 'fixed', location: 'hospital' } } } },
      { id: 'store-splint', text: 'Store the splint and add one hospital noise.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'hospital' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f42',
    name: 'The Unfinished Repair',
    story: 'A half-repaired gate is left open, its tools arranged in a line on the snow.',
    trigger: { event: 'survivorKilled' },
    options: [
      { id: 'finish-gate', text: 'Finish the repair and place one colony barricade.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
      { id: 'move-tools', text: 'Move the tools inside and spend one food on the crew, if able.', requires: { kind: 'food', atLeast: 1 }, outcome: { kind: 'adjustFood', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f43',
    name: 'The Last Footstep',
    story: 'The last footstep in the corridor stops at a door that nobody remembers locking.',
    trigger: { event: 'survivorKilled' },
    options: [
      { id: 'open-door', text: 'Open the door and remove one colony zombie, if able.', requires: { kind: 'zombiesAt', location: { kind: 'colony' }, atLeast: 1 }, outcome: { kind: 'removeZombies', count: 1, location: { kind: 'colony' } } },
      { id: 'brace-door', text: 'Brace the door and add one colony noise.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: true,
    nonCooperative: false,
  },
  {
    id: 'xr-f44',
    name: 'The Candle Vigil',
    story: 'A candle is kept burning beside the empty bunk until the wax reaches the floor.',
    trigger: { event: 'survivorKilled' },
    options: [
      { id: 'keep-vigil', text: 'Keep the vigil and raise morale by one.', outcome: { kind: 'adjustMorale', amount: 1 } },
      { id: 'save-wax', text: 'Save the wax and add one starvation token.', outcome: { kind: 'addStarvation', amount: 1 } },
    ],
    matureContent: true,
    nonCooperative: false,
  },
  {
    id: 'xr-f45',
    name: 'A New Name on the List',
    story: 'The roster gains one new line, then the pencil breaks before the writer can add a date.',
    trigger: { event: 'survivorKilled' },
    options: [
      { id: 'finish-roster', text: 'Finish the roster and remove one colony noise, if able.', outcome: { kind: 'ifAble', effect: { kind: 'removeNoise', count: 1, location: { kind: 'colony' } } } },
      { id: 'close-roster', text: 'Close the roster and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f46',
    name: 'The Searcher’s String',
    story: 'A string trail leads from the library stacks to a locked drawer at the colony.',
    trigger: { event: 'searchPerformed' },
    options: [
      { id: 'follow-string', text: 'Follow the string and add one library barricade.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'fixed', location: 'library' } } },
      { id: 'cut-string', text: 'Cut the string and add one library noise.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'library' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f47',
    name: 'Cold Aisle Discovery',
    story: 'A search through a grocery aisle finds a freezer door open and a single shelf still dry.',
    trigger: { event: 'searchPerformed' },
    options: [
      { id: 'take-shelf', text: 'Take the dry goods and add one food to the stores.', outcome: { kind: 'adjustFood', amount: 1 } },
      { id: 'close-freezer', text: 'Close the freezer and add one grocery-store noise.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'grocery-store' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f48',
    name: 'A Map Without Roads',
    story: 'A search uncovers a map whose roads have been rubbed away, leaving only the location names.',
    trigger: { event: 'searchPerformed' },
    options: [
      { id: 'draw-roads', text: 'Draw new roads and raise morale by one.', outcome: { kind: 'adjustMorale', amount: 1 } },
      { id: 'keep-map', text: 'Keep the map private and add one colony noise.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f49',
    name: 'The Radio Battery',
    story: 'A search finds a radio battery wrapped in a note that says, “For the next voice.”',
    trigger: { event: 'searchPerformed' },
    options: [
      { id: 'power-radio', text: 'Power the radio and raise morale by one.', outcome: { kind: 'adjustMorale', amount: 1 } },
      { id: 'save-battery', text: 'Save the battery and add one food to the colony stores.', outcome: { kind: 'adjustFood', amount: 1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f50',
    name: 'A School Bell in the Snow',
    story: 'The school bell rings once when the search team opens a cupboard beneath it.',
    trigger: { event: 'searchPerformed' },
    options: [
      { id: 'answer-bell', text: 'Answer the bell and add one school barricade.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'fixed', location: 'school' } } },
      { id: 'silence-bell', text: 'Silence the bell and add one school noise.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'school' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f51',
    name: 'The Pharmacy Ledger',
    story: 'A pharmacy ledger lists one final dose, but the patient line beside it is blank.',
    trigger: { event: 'searchPerformed' },
    options: [
      { id: 'reserve-dose', text: 'Reserve the dose and heal the least-influential hospital survivor, if one is there.', requires: { kind: 'survivorsAt', location: { kind: 'fixed', location: 'hospital' }, atLeast: 1 }, outcome: { kind: 'heal', amount: 1, target: { kind: 'lowestInfluenceAt', location: { kind: 'fixed', location: 'hospital' } } } },
      { id: 'burn-ledger', text: 'Burn the ledger and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: true,
    nonCooperative: false,
  },
  {
    id: 'xr-f52',
    name: 'Under the Library Rug',
    story: 'The search team finds a trail of salt beneath the library rug leading toward the stacks.',
    trigger: { event: 'searchPerformed' },
    options: [
      { id: 'salt-trail', text: 'Follow the salt and remove one library noise, if able.', outcome: { kind: 'ifAble', effect: { kind: 'removeNoise', count: 1, location: { kind: 'fixed', location: 'library' } } } },
      { id: 'cover-trail', text: 'Cover the trail and add one library barricade.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'fixed', location: 'library' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f53',
    name: 'After the Count',
    story: 'The crisis count is finished, but one contributor keeps a hand on the table.',
    trigger: { event: 'crisisResolved', crisisOutcome: 'any' },
    options: [
      { id: 'thank-contributors', text: 'Thank the contributors and raise morale by one.', outcome: { kind: 'adjustMorale', amount: 1 } },
      { id: 'secure-table', text: 'Secure the table and add one colony barricade.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f54',
    name: 'The Failed Alarm',
    story: 'The crisis alarm fails after the resolution, leaving the colony to choose its own warning.',
    trigger: { event: 'crisisResolved', crisisOutcome: 'failed' },
    options: [
      { id: 'sound-warning', text: 'Sound a warning and add one colony noise.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'colony' } } },
      { id: 'save-breath', text: 'Save everyone’s breath and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f55',
    name: 'A Narrow Success',
    story: 'The crisis is prevented by one card, and the colony argues about whether that was enough.',
    trigger: { event: 'crisisResolved', crisisOutcome: 'prevented' },
    options: [
      { id: 'celebrate', text: 'Celebrate the narrow success and raise morale by one.', outcome: { kind: 'adjustMorale', amount: 1 } },
      { id: 'recheck-gates', text: 'Recheck the gates and add one barricade at the colony.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f56',
    name: 'Cards on the Floor',
    story: 'The resolved crisis leaves a scatter of cards on the floor and a draft under the door.',
    trigger: { event: 'crisisResolved', crisisOutcome: 'any' },
    options: [
      { id: 'gather-cards', text: 'Gather the cards and remove one colony noise, if able.', outcome: { kind: 'ifAble', effect: { kind: 'removeNoise', count: 1, location: { kind: 'colony' } } } },
      { id: 'follow-draft', text: 'Follow the draft and add one colony noise.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f57',
    name: 'The Cost of Relief',
    story: 'The crisis relief arrives with a cost written in a language nobody can translate.',
    trigger: { event: 'crisisResolved', crisisOutcome: 'failed' },
    options: [
      { id: 'pay-cost', text: 'Pay the cost and spend one food, if able.', requires: { kind: 'food', atLeast: 1 }, outcome: { kind: 'adjustFood', amount: -1 } },
      { id: 'refuse-cost', text: 'Refuse the cost and add one starvation token.', outcome: { kind: 'addStarvation', amount: 1 } },
    ],
    matureContent: true,
    nonCooperative: false,
  },
  {
    id: 'xr-f58',
    name: 'The Uneven Share',
    story: 'The crisis stores are divided, and one player quietly receives a larger share than the others.',
    trigger: { event: 'crisisResolved', crisisOutcome: 'prevented' },
    options: [
      { id: 'accept-share', text: 'Accept the uneven share and raise morale by one.', outcome: { kind: 'adjustMorale', amount: 1 } },
      { id: 'even-share', text: 'Even the share and add one food to the colony stores.', outcome: { kind: 'adjustFood', amount: 1 } },
    ],
    matureContent: false,
    nonCooperative: true,
  },
  {
    id: 'xr-f59',
    name: 'The Quiet Ledger',
    story: 'The crisis ledger closes with no signature, only a thumbprint in the margin.',
    trigger: { event: 'crisisResolved', crisisOutcome: 'any' },
    options: [
      { id: 'seal-ledger', text: 'Seal the ledger and place one colony barricade.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
      { id: 'leave-ledger', text: 'Leave it open and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f60',
    name: 'A Small Rise',
    story: 'Morale rises just enough for the watch to sing a line before the cold takes their voices.',
    trigger: { event: 'moraleChanged', moraleDirection: 'up' },
    options: [
      { id: 'sing-line', text: 'Sing the line through and raise morale by one more.', outcome: { kind: 'adjustMorale', amount: 1 } },
      { id: 'save-voices', text: 'Save the voices and add one colony noise as the watch disperses.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f61',
    name: 'The Morale Bell',
    story: 'The morale bell rings twice after the count, and the second ring sounds farther away.',
    trigger: { event: 'moraleChanged', moraleDirection: 'up' },
    options: [
      { id: 'ring-again', text: 'Ring the bell again and place one colony barricade.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
      { id: 'muffle-bell', text: 'Muffle the bell and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f62',
    name: 'A Downward Draft',
    story: 'Morale dips when a draft extinguishes the colony’s only hallway candle.',
    trigger: { event: 'moraleChanged', moraleDirection: 'down' },
    options: [
      { id: 'relight', text: 'Relight the candle and add one food to the stores.', outcome: { kind: 'adjustFood', amount: 1 } },
      { id: 'close-hallway', text: 'Close the hallway and add one colony noise.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f63',
    name: 'The Comfort Ration',
    story: 'A morale drop leaves a comfort ration on the counter, wrapped in a page from an old diary.',
    trigger: { event: 'moraleChanged', moraleDirection: 'down' },
    options: [
      { id: 'serve-ration', text: 'Serve the comfort ration and spend one food to raise morale by one.', requires: { kind: 'food', atLeast: 1 }, outcome: { kind: 'sequence', effects: [{ kind: 'adjustFood', amount: -1 }, { kind: 'adjustMorale', amount: 1 }] } },
      { id: 'save-ration', text: 'Save it for a worse night and add one starvation token.', outcome: { kind: 'addStarvation', amount: 1 } },
    ],
    matureContent: true,
    nonCooperative: false,
  },
  {
    id: 'xr-f64',
    name: 'The Patient Watch',
    story: 'The colony accepts a hard truth quietly, and the watch waits for the next sound.',
    trigger: { event: 'moraleChanged', moraleDirection: 'any' },
    options: [
      { id: 'stand-together', text: 'Stand together and place one colony barricade.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
      { id: 'keep-distance', text: 'Keep your distance and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f65',
    name: 'A Better Story',
    story: 'The colony retells a small success until the story grows larger than the room.',
    trigger: { event: 'moraleChanged', moraleDirection: 'up' },
    options: [
      { id: 'tell-story', text: 'Tell the better story and raise morale by one.', outcome: { kind: 'adjustMorale', amount: 1 } },
      { id: 'write-story', text: 'Write it down for later and add one library noise.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'library' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f66',
    name: 'The Quiet Applause',
    story: 'A quiet applause travels through the colony after the morale track moves upward.',
    trigger: { event: 'moraleChanged', moraleDirection: 'up' },
    options: [
      { id: 'join-applause', text: 'Join the applause and add one colony food.', outcome: { kind: 'adjustFood', amount: 1 } },
      { id: 'keep-watch', text: 'Keep watch instead and place one colony barricade.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f67',
    name: 'Round-End Frost',
    story: 'At the end of the round, frost closes the outside latch before anyone reaches it.',
    trigger: { event: 'roundEnd' },
    options: [
      { id: 'thaw-latch', text: 'Thaw the latch and add one colony barricade.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
      { id: 'wait-thaw', text: 'Wait for daylight and add one starvation token.', outcome: { kind: 'addStarvation', amount: 1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f68',
    name: 'The Round-End Inventory',
    story: 'The round-end inventory finds one crate listed twice and another crate not listed at all.',
    trigger: { event: 'roundEnd' },
    options: [
      { id: 'correct-inventory', text: 'Correct the inventory and add one food to the stores.', outcome: { kind: 'adjustFood', amount: 1 } },
      { id: 'lock-crates', text: 'Lock the crates and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f69',
    name: 'Footprints at Midnight',
    story: 'The round ends with footprints around the colony, but none cross the threshold.',
    trigger: { event: 'roundEnd' },
    options: [
      { id: 'salt-threshold', text: 'Salt the threshold and add one colony noise.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'colony' } } },
      { id: 'guard-threshold', text: 'Guard the threshold and place one colony barricade.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f70',
    name: 'The Long Dawn',
    story: 'Dawn refuses to arrive at the end of the round, leaving the colony lit by blue snow.',
    trigger: { event: 'roundEnd' },
    options: [
      { id: 'keep-lights', text: 'Keep the lights burning and spend one food, if able.', requires: { kind: 'food', atLeast: 1 }, outcome: { kind: 'adjustFood', amount: -1 } },
      { id: 'save-lights', text: 'Save the fuel and add one starvation token.', outcome: { kind: 'addStarvation', amount: 1 } },
    ],
    matureContent: true,
    nonCooperative: false,
  },
  {
    id: 'xr-f71',
    name: 'The Empty Snowbank',
    story: 'The snowbank beside the colony collapses at round end, revealing a path that was not there before.',
    trigger: { event: 'roundEnd' },
    options: [
      { id: 'mark-path', text: 'Mark the path and raise morale by one.', outcome: { kind: 'adjustMorale', amount: 1 } },
      { id: 'cover-path', text: 'Cover the path and add one colony barricade.', outcome: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } } },
    ],
    matureContent: false,
    nonCooperative: false,
  },
  {
    id: 'xr-f72',
    name: 'The Unsent Letter',
    story: 'An unsent letter is found in the round-end post box, addressed to someone beyond the fence.',
    trigger: { event: 'roundEnd' },
    options: [
      { id: 'send-letter', text: 'Send the letter and add one noise at the colony.', outcome: { kind: 'addNoise', count: 1, location: { kind: 'colony' } } },
      { id: 'keep-letter', text: 'Keep the letter and lower morale by one.', outcome: { kind: 'adjustMorale', amount: -1 } },
    ],
    matureContent: false,
    nonCooperative: true,
  },
  {
    id: 'xr-f73',
    name: 'Bev Russell',
    story: 'Bev Russell returns from the edge of the colony with one more decision for the raiding party.',
    trigger: { event: 'moveCompleted', destination: 'any' },
    options: [
      {
        id: 'raiding-party',
        text: 'Join the raiding party and mark Bev Russell’s applicable option.',
        outcome: { kind: 'adjustCounter', counter: 'bevRussellOptions', amount: 1 },
      },
    ],
    matureContent: false,
    nonCooperative: false,
  },
];
