import type { ItemCardDefinition } from '../schema.js';

/**
 * The six location decks — 20 cards each, §2.0.
 *
 * These cards are original content. The named §18 item cards remain in the
 * starter deck, so none of their ids, names, or definitions belong here.
 */
export const BASE_LOCATION_ITEMS: ItemCardDefinition[] = [
  /* ------------------------------------------------------------------ *
   * Police station
   * ------------------------------------------------------------------ */
  {
    id: 'it-ps-evidence-seal',
    name: 'Evidence Seal',
    text: 'Place one barricade at your location, then remove one noise token there.',
    symbols: ['tool', 'education'],
    deck: 'police-station',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'addBarricade', count: 1, location: { kind: 'sourceLocation' } },
        { kind: 'removeNoise', count: 1, location: { kind: 'sourceLocation' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-ps-zip-ties',
    name: 'Zip Ties',
    text: 'Equipped survivor: once per round, remove one zombie from this location. This is not a kill.',
    symbols: ['tool'],
    deck: 'police-station',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'zip-ties-restraint',
        text: 'Remove one zombie from this location. This is not a kill.',
        location: 'police-station',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'removeZombies',
          count: 1,
          location: { kind: 'sourceLocation' },
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-ps-flare-gun',
    name: 'Flare Gun',
    text: 'Equipped survivor: once per game, kill one zombie at this location and roll exposure for that kill.',
    symbols: ['weapon', 'fuel'],
    deck: 'police-station',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'flare-gun-shot',
        text: 'Kill one zombie at this location and roll exposure for that kill.',
        location: 'police-station',
        dieThreshold: null,
        usage: 'oncePerGame',
        effect: {
          kind: 'killZombies',
          count: 1,
          location: { kind: 'sourceLocation' },
          isAttack: false,
          rollExposure: true,
          killer: { kind: 'source' },
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-ps-body-armor',
    name: 'Body Armor',
    text: 'Equipped survivor: once per round, place one barricade at this location and add one noise there.',
    symbols: ['tool', 'survivor'],
    deck: 'police-station',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'body-armor-fortify',
        text: 'Place one barricade at this location and add one noise there.',
        location: 'police-station',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'sequence',
          effects: [
            { kind: 'addBarricade', count: 1, location: { kind: 'sourceLocation' } },
            { kind: 'addNoise', count: 1, location: { kind: 'sourceLocation' } },
          ],
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-ps-bulletin-board',
    name: 'Bulletin Board Clippings',
    text: 'Draw one card from the police-station deck.',
    symbols: ['education'],
    deck: 'police-station',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'drawItems',
      to: { kind: 'effectController' },
      deck: { kind: 'locationItems', location: 'police-station' },
      count: 1,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-ps-incident-report',
    name: 'Incident Report',
    text: 'Draw two cards from the police-station deck, then discard one card from your hand.',
    symbols: ['education', 'tool'],
    deck: 'police-station',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'drawItems',
          to: { kind: 'effectController' },
          deck: { kind: 'locationItems', location: 'police-station' },
          count: 2,
        },
        { kind: 'discardItems', from: { kind: 'effectController' }, count: 1 },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-ps-nightstick',
    name: 'Nightstick',
    text: 'Equipped survivor: once per round, kill one zombie at this location and roll exposure for that kill.',
    symbols: ['weapon', 'tool'],
    deck: 'police-station',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'nightstick-sweep',
        text: 'Kill one zombie at this location and roll exposure for that kill.',
        location: 'police-station',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'killZombies',
          count: 1,
          location: { kind: 'sourceLocation' },
          isAttack: false,
          rollExposure: true,
          killer: { kind: 'source' },
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-ps-breach-charge',
    name: 'Breach Charge',
    text: 'Kill up to two zombies at your location and roll exposure for each kill.',
    symbols: ['weapon', 'tool'],
    deck: 'police-station',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'killZombies',
      count: 2,
      location: { kind: 'sourceLocation' },
      isAttack: false,
      rollExposure: true,
      killer: { kind: 'source' },
    },
    nonCooperative: false,
    matureContent: true,
  },
  {
    id: 'it-ps-traffic-cone',
    name: 'Traffic Cone',
    text: 'Remove up to two noise tokens from your location, then add one noise token at the police station.',
    symbols: ['tool'],
    deck: 'police-station',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'removeNoise', count: 2, location: { kind: 'sourceLocation' } },
        { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'police-station' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-ps-cold-case-file',
    name: 'Cold Case File',
    text: 'Equipped survivor: once per round, draw one card from the police-station deck.',
    symbols: ['education'],
    deck: 'police-station',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'cold-case-lead',
        text: 'Draw one card from the police-station deck.',
        location: 'police-station',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'drawItems',
          to: { kind: 'effectController' },
          deck: { kind: 'locationItems', location: 'police-station' },
          count: 1,
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-ps-prisoner-transfer',
    name: 'Prisoner Transfer Van',
    text: 'Move one survivor you control to the colony and roll exposure for that move.',
    symbols: ['survivor', 'fuel'],
    deck: 'police-station',
    textKind: 'outsider',
    kind: 'oneShot',
    onPlay: {
      kind: 'moveSurvivor',
      target: {
        kind: 'chosen',
        by: { kind: 'effectController' },
        among: { kind: 'allControlledBy', player: { kind: 'effectController' } },
      },
      to: { kind: 'colony' },
      rollExposure: true,
      consumesMoveAllowance: false,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-ps-radio',
    name: 'Portable Radio',
    text: 'Move one survivor you control to the colony without rolling exposure; this does not use that survivor’s move.',
    symbols: ['tool', 'fuel'],
    deck: 'police-station',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'moveSurvivor',
      target: {
        kind: 'chosen',
        by: { kind: 'effectController' },
        among: { kind: 'allControlledBy', player: { kind: 'effectController' } },
      },
      to: { kind: 'colony' },
      rollExposure: false,
      consumesMoveAllowance: false,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-ps-wanted-poster',
    name: 'Wanted Poster',
    text: 'Add one noise token at the police station, then add one food to the colony.',
    symbols: ['education', 'food'],
    deck: 'police-station',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'police-station' } },
        { kind: 'adjustFood', amount: 1 },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-ps-confiscated-property',
    name: 'Confiscated Property',
    text: 'Take a random card from another player, then lower morale by one.',
    symbols: ['tool', 'weapon'],
    deck: 'police-station',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'stealRandomCard',
          from: { kind: 'chosen', by: { kind: 'effectController' }, among: 'otherPlayers' },
          to: { kind: 'effectController' },
        },
        { kind: 'adjustMorale', amount: -1 },
      ],
    },
    nonCooperative: true,
    matureContent: false,
  },
  {
    id: 'it-ps-guard-shift',
    name: 'Guard Shift Roster',
    text: 'Equipped survivor: once per round, place one barricade at the colony.',
    symbols: ['tool', 'survivor'],
    deck: 'police-station',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'guard-shift-barricade',
        text: 'Place one barricade at the colony.',
        location: 'colony',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-ps-shelter-log',
    name: 'Shelter Logbook',
    text: 'Add one food to the colony. If a helpless survivor is already there, raise morale by one; otherwise add one helpless survivor.',
    symbols: ['education', 'survivor'],
    deck: 'police-station',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'adjustFood', amount: 1 },
        {
          kind: 'branch',
          test: { kind: 'helplessSurvivors', atLeast: 1 },
          then: { kind: 'adjustMorale', amount: 1 },
          otherwise: { kind: 'addHelpless', count: 1 },
        },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-ps-dispatch-tape',
    name: 'Dispatch Tape',
    text: 'Remove up to three zombies from your location. These removals are not kills.',
    symbols: ['tool', 'education'],
    deck: 'police-station',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'removeZombies',
      count: 3,
      location: { kind: 'sourceLocation' },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-ps-locked-drawer',
    name: 'Locked Drawer',
    text: 'Equipped survivor: once per round, either place one barricade at this location or remove one zombie from this location. The removal is not a kill.',
    symbols: ['tool'],
    deck: 'police-station',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'locked-drawer-choice',
        text: 'Either place one barricade here or remove one zombie here. The removal is not a kill.',
        location: 'police-station',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'choice',
          prompt: 'Locked Drawer',
          chooser: { kind: 'effectController' },
          options: [
            {
              id: 'drawer-barricade',
              text: 'Place one barricade at this location.',
              outcome: { kind: 'addBarricade', count: 1, location: { kind: 'sourceLocation' } },
            },
            {
              id: 'drawer-remove',
              text: 'Remove one zombie from this location. This is not a kill.',
              outcome: { kind: 'removeZombies', count: 1, location: { kind: 'sourceLocation' } },
            },
          ],
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-ps-crime-scene-tape',
    name: 'Crime Scene Tape',
    text: 'Place one barricade at your location, remove one noise token there, then add one noise token at the police station.',
    symbols: ['tool', 'education'],
    deck: 'police-station',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'addBarricade', count: 1, location: { kind: 'sourceLocation' } },
        { kind: 'removeNoise', count: 1, location: { kind: 'sourceLocation' } },
        { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'police-station' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-ps-last-resort',
    name: 'Last Resort',
    text: 'If able, wound one survivor at your location. Then kill one zombie there without rolling exposure.',
    symbols: ['weapon', 'survivor'],
    deck: 'police-station',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'ifAble',
          effect: {
            kind: 'wound',
            target: {
              kind: 'chosen',
              by: { kind: 'effectController' },
              among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
            },
            amount: 1,
          },
        },
        {
          kind: 'killZombies',
          count: 1,
          location: { kind: 'sourceLocation' },
          isAttack: false,
          rollExposure: false,
          killer: { kind: 'source' },
        },
      ],
    },
    nonCooperative: false,
    matureContent: true,
  },

  /* ------------------------------------------------------------------ *
   * Grocery store
   * ------------------------------------------------------------------ */
  {
    id: 'it-gs-aisle-map',
    name: 'Aisle Map',
    text: 'Draw one card from the grocery-store deck, then add one noise token at your location.',
    symbols: ['education', 'food'],
    deck: 'grocery-store',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'drawItems',
          to: { kind: 'effectController' },
          deck: { kind: 'locationItems', location: 'grocery-store' },
          count: 1,
        },
        { kind: 'addNoise', count: 1, location: { kind: 'sourceLocation' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gs-freezer-key',
    name: 'Freezer Key',
    text: 'Equipped survivor: once per round, remove one zombie from this location. This is not a kill.',
    symbols: ['tool', 'food'],
    deck: 'grocery-store',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'freezer-key-lock',
        text: 'Remove one zombie from this location. This is not a kill.',
        location: 'grocery-store',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: { kind: 'removeZombies', count: 1, location: { kind: 'sourceLocation' } },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gs-canned-stew',
    name: 'Canned Stew',
    text: 'Add two food to the colony and lower morale by one.',
    symbols: ['food'],
    deck: 'grocery-store',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'adjustFood', amount: 2 },
        { kind: 'adjustMorale', amount: -1 },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gs-spoilage-bin',
    name: 'Spoilage Bin',
    text: 'Remove one food from the colony, then heal one wound from a survivor at your location.',
    symbols: ['food', 'medicine'],
    deck: 'grocery-store',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'adjustFood', amount: -1 },
        {
          kind: 'heal',
          target: {
            kind: 'chosen',
            by: { kind: 'effectController' },
            among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
          },
          amount: 1,
        },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gs-salt-sacks',
    name: 'Salt Sacks',
    text: 'Add one food to the colony, then place one barricade at your location.',
    symbols: ['food', 'tool'],
    deck: 'grocery-store',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'adjustFood', amount: 1 },
        { kind: 'addBarricade', count: 1, location: { kind: 'sourceLocation' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gs-shopping-cart',
    name: 'Shopping Cart',
    text: 'Equipped survivor: once per round, move this survivor to the colony; the move does not use their allowance, but it rolls exposure.',
    symbols: ['tool', 'survivor'],
    deck: 'grocery-store',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'shopping-cart-rush',
        text: 'Move this survivor to the colony; the move does not use their allowance, but it rolls exposure.',
        location: 'grocery-store',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'moveSurvivor',
          target: { kind: 'source' },
          to: { kind: 'colony' },
          rollExposure: true,
          consumesMoveAllowance: false,
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gs-coupon-book',
    name: 'Coupon Book',
    text: 'Add one food to the colony. If morale is three or lower, raise morale by two; otherwise raise it by one.',
    symbols: ['food', 'education'],
    deck: 'grocery-store',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'adjustFood', amount: 1 },
        {
          kind: 'branch',
          test: { kind: 'morale', atMost: 3 },
          then: { kind: 'adjustMorale', amount: 2 },
          otherwise: { kind: 'adjustMorale', amount: 1 },
        },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gs-stockroom-lamp',
    name: 'Stockroom Lamp',
    text: 'Equipped survivor: once per round, remove up to two noise tokens from this location, then add one noise token at the grocery store.',
    symbols: ['fuel', 'tool'],
    deck: 'grocery-store',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'stockroom-lamp-clear',
        text: 'Remove up to two noise tokens from this location, then add one noise token at the grocery store.',
        location: 'grocery-store',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'sequence',
          effects: [
            { kind: 'removeNoise', count: 2, location: { kind: 'sourceLocation' } },
            { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'grocery-store' } },
          ],
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gs-freezer-burn',
    name: 'Freezer-Burned Box',
    text: 'Add three food to the colony, then wound one survivor at your location.',
    symbols: ['food', 'medicine'],
    deck: 'grocery-store',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'adjustFood', amount: 3 },
        {
          kind: 'wound',
          target: {
            kind: 'chosen',
            by: { kind: 'effectController' },
            among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
          },
          amount: 1,
        },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gs-cash-drawer',
    name: 'Cash Drawer',
    text: 'Take a random card from another player, then lower morale by one.',
    symbols: ['tool', 'weapon'],
    deck: 'grocery-store',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'stealRandomCard',
          from: { kind: 'chosen', by: { kind: 'effectController' }, among: 'otherPlayers' },
          to: { kind: 'effectController' },
        },
        { kind: 'adjustMorale', amount: -1 },
      ],
    },
    nonCooperative: true,
    matureContent: false,
  },
  {
    id: 'it-gs-delivery-schedule',
    name: 'Delivery Schedule',
    text: 'Draw one card from the grocery-store deck, then add one food to the colony.',
    symbols: ['fuel', 'food'],
    deck: 'grocery-store',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'drawItems',
          to: { kind: 'effectController' },
          deck: { kind: 'locationItems', location: 'grocery-store' },
          count: 1,
        },
        { kind: 'adjustFood', amount: 1 },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gs-sample-cup',
    name: 'Sample Cup',
    text: 'Heal one wound from a survivor at your location, then add one noise token there.',
    symbols: ['medicine', 'food'],
    deck: 'grocery-store',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'heal',
          target: {
            kind: 'chosen',
            by: { kind: 'effectController' },
            among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
          },
          amount: 1,
        },
        { kind: 'addNoise', count: 1, location: { kind: 'sourceLocation' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gs-window-ad',
    name: 'Window Advertisement',
    text: 'Add two noise tokens at the grocery store.',
    symbols: ['fuel', 'education'],
    deck: 'grocery-store',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: { kind: 'addNoise', count: 2, location: { kind: 'fixed', location: 'grocery-store' } },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gs-employee-badge',
    name: 'Employee Badge',
    text: 'Equipped survivor: once per round, draw one card from the grocery-store deck.',
    symbols: ['survivor', 'education'],
    deck: 'grocery-store',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'employee-badge-access',
        text: 'Draw one card from the grocery-store deck.',
        location: 'grocery-store',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'drawItems',
          to: { kind: 'effectController' },
          deck: { kind: 'locationItems', location: 'grocery-store' },
          count: 1,
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gs-ice-melt',
    name: 'Ice Melt Tub',
    text: 'Remove up to two noise tokens from the grocery store, then add one food to the colony.',
    symbols: ['fuel', 'food'],
    deck: 'grocery-store',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'removeNoise', count: 2, location: { kind: 'fixed', location: 'grocery-store' } },
        { kind: 'adjustFood', amount: 1 },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gs-produce-crate',
    name: 'Produce Crate',
    text: 'Equipped survivor: once per round, add one food to the colony.',
    symbols: ['food', 'survivor'],
    deck: 'grocery-store',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'produce-crate-share',
        text: 'Add one food to the colony.',
        location: 'grocery-store',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: { kind: 'adjustFood', amount: 1 },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gs-meat-hook',
    name: 'Meat Hook',
    text: 'Equipped survivor: once per round, kill one zombie at this location and roll exposure for that kill.',
    symbols: ['weapon', 'tool'],
    deck: 'grocery-store',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'meat-hook-swing',
        text: 'Kill one zombie at this location and roll exposure for that kill.',
        location: 'grocery-store',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'killZombies',
          count: 1,
          location: { kind: 'sourceLocation' },
          isAttack: false,
          rollExposure: true,
          killer: { kind: 'source' },
        },
      },
    ],
    nonCooperative: false,
    matureContent: true,
  },
  {
    id: 'it-gs-returns-counter',
    name: 'Returns Counter',
    text: 'If able, discard one card from your hand. Then draw two cards from the grocery-store deck.',
    symbols: ['tool', 'food'],
    deck: 'grocery-store',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'ifAble', effect: { kind: 'discardItems', from: { kind: 'effectController' }, count: 1 } },
        {
          kind: 'drawItems',
          to: { kind: 'effectController' },
          deck: { kind: 'locationItems', location: 'grocery-store' },
          count: 2,
        },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gs-hearty-leftovers',
    name: 'Hearty Leftovers',
    text: 'If the colony has food, remove one food and heal one wound from a survivor here; otherwise add one starvation token.',
    symbols: ['food', 'medicine'],
    deck: 'grocery-store',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'branch',
      test: { kind: 'food', atLeast: 1 },
      then: {
        kind: 'sequence',
        effects: [
          { kind: 'adjustFood', amount: -1 },
          {
            kind: 'heal',
            target: {
              kind: 'chosen',
              by: { kind: 'effectController' },
              among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
            },
            amount: 1,
          },
        ],
      },
      otherwise: { kind: 'addStarvation', amount: 1 },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gs-discount-stickers',
    name: 'Discount Stickers',
    text: 'If morale is three or lower, add two food to the colony; otherwise add one food and raise morale by one.',
    symbols: ['food', 'education'],
    deck: 'grocery-store',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'branch',
      test: { kind: 'morale', atMost: 3 },
      then: { kind: 'adjustFood', amount: 2 },
      otherwise: {
        kind: 'sequence',
        effects: [
          { kind: 'adjustFood', amount: 1 },
          { kind: 'adjustMorale', amount: 1 },
        ],
      },
    },
    nonCooperative: false,
    matureContent: false,
  },

  /* ------------------------------------------------------------------ *
   * School
   * ------------------------------------------------------------------ */
  {
    id: 'it-school-textbook',
    name: 'Emergency Textbook',
    text: 'Equipped survivor: once per round, draw one card from the school deck.',
    symbols: ['education'],
    deck: 'school',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'textbook-research',
        text: 'Draw one card from the school deck.',
        location: 'school',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'drawItems',
          to: { kind: 'effectController' },
          deck: { kind: 'locationItems', location: 'school' },
          count: 1,
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-school-science-kit',
    name: 'Science Kit',
    text: 'Roll a die. On 4+, heal one wound from a survivor here; otherwise add one noise at the school.',
    symbols: ['education', 'medicine'],
    deck: 'school',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'rollDie', sides: 6, store: 'science-kit' },
        {
          kind: 'branch',
          test: { kind: 'variable', name: 'science-kit', atLeast: 4 },
          then: {
            kind: 'heal',
            target: {
              kind: 'chosen',
              by: { kind: 'effectController' },
              among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
            },
            amount: 1,
          },
          otherwise: { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'school' } },
        },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-school-fire-extinguisher',
    name: 'Fire Extinguisher',
    text: 'Equipped survivor: once per round, remove up to two noise tokens from this location.',
    symbols: ['tool'],
    deck: 'school',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'fire-extinguisher-clear',
        text: 'Remove up to two noise tokens from this location.',
        location: 'school',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: { kind: 'removeNoise', count: 2, location: { kind: 'sourceLocation' } },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-school-locker-key',
    name: 'Locker Key',
    text: 'Draw two cards from the school deck, then discard one card from your hand.',
    symbols: ['tool', 'education'],
    deck: 'school',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'drawItems',
          to: { kind: 'effectController' },
          deck: { kind: 'locationItems', location: 'school' },
          count: 2,
        },
        { kind: 'discardItems', from: { kind: 'effectController' }, count: 1 },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-school-lunch-tray',
    name: 'Lunch Tray',
    text: 'Add one food to the colony, then remove one noise token from your location.',
    symbols: ['food', 'tool'],
    deck: 'school',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'adjustFood', amount: 1 },
        { kind: 'removeNoise', count: 1, location: { kind: 'sourceLocation' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-school-art-supplies',
    name: 'Art Supplies',
    text: 'Place one barricade at your location, then raise morale by one.',
    symbols: ['education', 'tool'],
    deck: 'school',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'addBarricade', count: 1, location: { kind: 'sourceLocation' } },
        { kind: 'adjustMorale', amount: 1 },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-school-gym-rope',
    name: 'Gym Rope',
    text: 'Equipped survivor: once per round, move this survivor to the colony without rolling exposure; this does not use their move.',
    symbols: ['tool', 'survivor'],
    deck: 'school',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'gym-rope-rescue',
        text: 'Move this survivor to the colony without rolling exposure; this does not use their move.',
        location: 'school',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'moveSurvivor',
          target: { kind: 'source' },
          to: { kind: 'colony' },
          rollExposure: false,
          consumesMoveAllowance: false,
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-school-attendance-sheet',
    name: 'Attendance Sheet',
    text: 'Add one helpless survivor to the colony, if there is room.',
    symbols: ['education', 'survivor'],
    deck: 'school',
    textKind: 'outsider',
    kind: 'oneShot',
    onPlay: { kind: 'addHelpless', count: 1 },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-school-nurses-pass',
    name: 'Nurse’s Pass',
    text: 'Heal one wound from a survivor at your location, removing frostbite first.',
    symbols: ['medicine', 'education'],
    deck: 'school',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'heal',
      target: {
        kind: 'chosen',
        by: { kind: 'effectController' },
        among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
      },
      amount: 1,
      frostbiteFirst: true,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-school-principal-keys',
    name: 'Principal’s Keys',
    text: 'Equipped survivor: once per round, place one barricade at this location.',
    symbols: ['tool', 'education'],
    deck: 'school',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'principals-keys-lockdown',
        text: 'Place one barricade at this location.',
        location: 'school',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: { kind: 'addBarricade', count: 1, location: { kind: 'sourceLocation' } },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-school-bus-pass',
    name: 'Bus Pass',
    text: 'Move one survivor you control to the colony without rolling exposure; this does not use that survivor’s move.',
    symbols: ['fuel', 'survivor'],
    deck: 'school',
    textKind: 'outsider',
    kind: 'oneShot',
    onPlay: {
      kind: 'moveSurvivor',
      target: {
        kind: 'chosen',
        by: { kind: 'effectController' },
        among: { kind: 'allControlledBy', player: { kind: 'effectController' } },
      },
      to: { kind: 'colony' },
      rollExposure: false,
      consumesMoveAllowance: false,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-school-detention-log',
    name: 'Detention Log',
    text: 'Take a random card from another player, then add one noise token at the school.',
    symbols: ['education', 'weapon'],
    deck: 'school',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'stealRandomCard',
          from: { kind: 'chosen', by: { kind: 'effectController' }, among: 'otherPlayers' },
          to: { kind: 'effectController' },
        },
        { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'school' } },
      ],
    },
    nonCooperative: true,
    matureContent: false,
  },
  {
    id: 'it-school-projector',
    name: 'Projector Lamp',
    text: 'Remove up to four noise tokens from the school, then add two noise tokens at the police station.',
    symbols: ['fuel', 'education'],
    deck: 'school',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'removeNoise', count: 4, location: { kind: 'fixed', location: 'school' } },
        { kind: 'addNoise', count: 2, location: { kind: 'fixed', location: 'police-station' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-school-emergency-drill',
    name: 'Emergency Drill Plan',
    text: 'Equipped survivor: once per round, place one barricade at the colony.',
    symbols: ['education', 'tool'],
    deck: 'school',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'emergency-drill-lockdown',
        text: 'Place one barricade at the colony.',
        location: 'colony',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-school-chalk-dust',
    name: 'Chalk Dust',
    text: 'Remove one zombie from the school, then add one noise token there. The removal is not a kill.',
    symbols: ['tool', 'education'],
    deck: 'school',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'removeZombies', count: 1, location: { kind: 'fixed', location: 'school' } },
        { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'school' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-school-chemistry-notes',
    name: 'Chemistry Notes',
    text: 'If you can discard a medicine card, discard it to kill one zombie at your location without rolling exposure; otherwise add one noise there.',
    symbols: ['education', 'medicine'],
    deck: 'school',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'branch',
      test: {
        kind: 'holdsCards',
        player: { kind: 'effectController' },
        requirement: { symbols: ['medicine'] },
        atLeast: 1,
      },
      then: {
        kind: 'sequence',
        effects: [
          {
            kind: 'discardItems',
            from: { kind: 'effectController' },
            count: 1,
            requirement: { symbols: ['medicine'] },
          },
          {
            kind: 'killZombies',
            count: 1,
            location: { kind: 'sourceLocation' },
            isAttack: false,
            rollExposure: false,
            killer: { kind: 'source' },
          },
        ],
      },
      otherwise: { kind: 'addNoise', count: 1, location: { kind: 'sourceLocation' } },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-school-janitor-cart',
    name: 'Janitor Cart',
    text: 'Equipped survivor: once per round, remove one noise token from this location, then place one barricade there.',
    symbols: ['tool'],
    deck: 'school',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'janitor-cart-work',
        text: 'Remove one noise token from this location, then place one barricade there.',
        location: 'school',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'sequence',
          effects: [
            { kind: 'removeNoise', count: 1, location: { kind: 'sourceLocation' } },
            { kind: 'addBarricade', count: 1, location: { kind: 'sourceLocation' } },
          ],
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-school-quiet-room',
    name: 'Quiet Room Key',
    text: 'Heal up to two wounds from one survivor at your location, then lower morale by one.',
    symbols: ['medicine', 'education'],
    deck: 'school',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'heal',
          target: {
            kind: 'chosen',
            by: { kind: 'effectController' },
            among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
          },
          amount: 2,
        },
        { kind: 'adjustMorale', amount: -1 },
      ],
    },
    nonCooperative: false,
    matureContent: true,
  },
  {
    id: 'it-school-bell-schedule',
    name: 'Bell Schedule',
    text: 'Add one noise token at every non-colony location.',
    symbols: ['education', 'tool'],
    deck: 'school',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: { kind: 'addNoise', count: 1, location: { kind: 'eachNonColony' } },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-school-contraband-box',
    name: 'Contraband Box',
    text: 'Take a random card from another player, then lower morale by one.',
    symbols: ['weapon', 'tool'],
    deck: 'school',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'stealRandomCard',
          from: { kind: 'chosen', by: { kind: 'effectController' }, among: 'otherPlayers' },
          to: { kind: 'effectController' },
        },
        { kind: 'adjustMorale', amount: -1 },
      ],
    },
    nonCooperative: true,
    matureContent: false,
  },

  /* ------------------------------------------------------------------ *
   * Gas station
   * ------------------------------------------------------------------ */
  {
    id: 'it-gas-pump-handle',
    name: 'Pump Handle',
    text: 'Add one round to the round tracker, then add one noise token at the gas station.',
    symbols: ['fuel', 'tool'],
    deck: 'gas-station',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'adjustRounds', amount: 1 },
        { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'gas-station' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gas-engine-oil',
    name: 'Engine Oil',
    text: 'Equipped survivor: once per round, place one barricade at this location and add one noise there.',
    symbols: ['fuel', 'tool'],
    deck: 'gas-station',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'engine-oil-fortify',
        text: 'Place one barricade at this location and add one noise there.',
        location: 'gas-station',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'sequence',
          effects: [
            { kind: 'addBarricade', count: 1, location: { kind: 'sourceLocation' } },
            { kind: 'addNoise', count: 1, location: { kind: 'sourceLocation' } },
          ],
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gas-tire-iron',
    name: 'Tire Iron',
    text: 'Equipped survivor: once per round, kill one zombie at this location and roll exposure for that kill.',
    symbols: ['weapon', 'tool'],
    deck: 'gas-station',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'tire-iron-swing',
        text: 'Kill one zombie at this location and roll exposure for that kill.',
        location: 'gas-station',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'killZombies',
          count: 1,
          location: { kind: 'sourceLocation' },
          isAttack: false,
          rollExposure: true,
          killer: { kind: 'source' },
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gas-road-atlas',
    name: 'Road Atlas',
    text: 'Move one survivor you control to the colony without rolling exposure; this does not use that survivor’s move.',
    symbols: ['fuel', 'education'],
    deck: 'gas-station',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'moveSurvivor',
      target: {
        kind: 'chosen',
        by: { kind: 'effectController' },
        among: { kind: 'allControlledBy', player: { kind: 'effectController' } },
      },
      to: { kind: 'colony' },
      rollExposure: false,
      consumesMoveAllowance: false,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gas-ethanol-can',
    name: 'Ethanol Can',
    text: 'Add one food to the colony, then add one noise token at the gas station.',
    symbols: ['fuel', 'food'],
    deck: 'gas-station',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'adjustFood', amount: 1 },
        { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'gas-station' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gas-jumper-cables',
    name: 'Jumper Cables',
    text: 'Move one survivor you control to the colony without rolling exposure; then add one noise token at the gas station.',
    symbols: ['fuel', 'tool'],
    deck: 'gas-station',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'moveSurvivor',
          target: {
            kind: 'chosen',
            by: { kind: 'effectController' },
            among: { kind: 'allControlledBy', player: { kind: 'effectController' } },
          },
          to: { kind: 'colony' },
          rollExposure: false,
          consumesMoveAllowance: false,
        },
        { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'gas-station' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gas-tow-chain',
    name: 'Tow Chain',
    text: 'Equipped survivor: once per round, remove one zombie from this location and add one noise there. The removal is not a kill.',
    symbols: ['tool', 'fuel'],
    deck: 'gas-station',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'tow-chain-drag',
        text: 'Remove one zombie from this location and add one noise there. The removal is not a kill.',
        location: 'gas-station',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'sequence',
          effects: [
            { kind: 'removeZombies', count: 1, location: { kind: 'sourceLocation' } },
            { kind: 'addNoise', count: 1, location: { kind: 'sourceLocation' } },
          ],
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gas-flashlight',
    name: 'Rechargeable Flashlight',
    text: 'Equipped survivor: once per round, remove up to two noise tokens from this location.',
    symbols: ['fuel', 'tool'],
    deck: 'gas-station',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'flashlight-sweep',
        text: 'Remove up to two noise tokens from this location.',
        location: 'gas-station',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: { kind: 'removeNoise', count: 2, location: { kind: 'sourceLocation' } },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gas-windshield-scraper',
    name: 'Windshield Scraper',
    text: 'Remove up to two noise tokens from your location, then place one barricade there.',
    symbols: ['tool', 'fuel'],
    deck: 'gas-station',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'removeNoise', count: 2, location: { kind: 'sourceLocation' } },
        { kind: 'addBarricade', count: 1, location: { kind: 'sourceLocation' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gas-employee-radio',
    name: 'Employee Radio',
    text: 'Draw one card from the gas-station deck, then lower morale by one.',
    symbols: ['fuel', 'tool'],
    deck: 'gas-station',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'drawItems',
          to: { kind: 'effectController' },
          deck: { kind: 'locationItems', location: 'gas-station' },
          count: 1,
        },
        { kind: 'adjustMorale', amount: -1 },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gas-parking-receipt',
    name: 'Parking Receipt',
    text: 'Draw two cards from the gas-station deck, then discard one card from your hand.',
    symbols: ['fuel', 'education'],
    deck: 'gas-station',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'drawItems',
          to: { kind: 'effectController' },
          deck: { kind: 'locationItems', location: 'gas-station' },
          count: 2,
        },
        { kind: 'discardItems', from: { kind: 'effectController' }, count: 1 },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gas-battery-pack',
    name: 'Battery Pack',
    text: 'Add one round to the round tracker, then add one noise token at the gas station.',
    symbols: ['fuel', 'tool'],
    deck: 'gas-station',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'adjustRounds', amount: 1 },
        { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'gas-station' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gas-propane-tank',
    name: 'Propane Tank',
    text: 'Kill up to two zombies at your location without rolling exposure, then add two noise tokens there.',
    symbols: ['fuel', 'weapon'],
    deck: 'gas-station',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'killZombies',
          count: 2,
          location: { kind: 'sourceLocation' },
          isAttack: false,
          rollExposure: false,
          killer: { kind: 'source' },
        },
        { kind: 'addNoise', count: 2, location: { kind: 'sourceLocation' } },
      ],
    },
    nonCooperative: false,
    matureContent: true,
  },
  {
    id: 'it-gas-wiper-fluid',
    name: 'Wiper Fluid',
    text: 'Heal one wound from a survivor at your location, then remove one noise token there.',
    symbols: ['medicine', 'fuel'],
    deck: 'gas-station',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'heal',
          target: {
            kind: 'chosen',
            by: { kind: 'effectController' },
            among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
          },
          amount: 1,
        },
        { kind: 'removeNoise', count: 1, location: { kind: 'sourceLocation' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gas-spare-keys',
    name: 'Spare Keys',
    text: 'Equipped survivor: once per round, draw one card from the gas-station deck.',
    symbols: ['tool', 'fuel'],
    deck: 'gas-station',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'spare-keys-access',
        text: 'Draw one card from the gas-station deck.',
        location: 'gas-station',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'drawItems',
          to: { kind: 'effectController' },
          deck: { kind: 'locationItems', location: 'gas-station' },
          count: 1,
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gas-service-manual',
    name: 'Service Manual',
    text: 'Equipped survivor: spend a 4+ die once per round to remove one zombie from this location. The removal is not a kill.',
    symbols: ['education', 'tool'],
    deck: 'gas-station',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'service-manual-procedure',
        text: 'Remove one zombie from this location. The removal is not a kill.',
        location: 'gas-station',
        dieThreshold: 4,
        usage: 'oncePerRound',
        effect: { kind: 'removeZombies', count: 1, location: { kind: 'sourceLocation' } },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gas-hot-coffee',
    name: 'Hot Coffee',
    text: 'Add one food to the colony, then raise morale by one.',
    symbols: ['food', 'fuel'],
    deck: 'gas-station',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'adjustFood', amount: 1 },
        { kind: 'adjustMorale', amount: 1 },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gas-closed-sign',
    name: 'Closed Sign',
    text: 'Remove all noise tokens from the gas station, then place up to two barricades there.',
    symbols: ['tool', 'fuel'],
    deck: 'gas-station',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'removeNoise', count: 4, location: { kind: 'fixed', location: 'gas-station' } },
        { kind: 'addBarricade', count: 2, location: { kind: 'fixed', location: 'gas-station' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-gas-cash-till',
    name: 'Cash Till',
    text: 'Take a random card from another player, then add one noise token at the gas station.',
    symbols: ['tool', 'weapon'],
    deck: 'gas-station',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'stealRandomCard',
          from: { kind: 'chosen', by: { kind: 'effectController' }, among: 'otherPlayers' },
          to: { kind: 'effectController' },
        },
        { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'gas-station' } },
      ],
    },
    nonCooperative: true,
    matureContent: false,
  },
  {
    id: 'it-gas-pit-crew',
    name: 'Pit Crew Roster',
    text: 'Add one helpless survivor to the colony, if there is room, then raise morale by one.',
    symbols: ['survivor', 'fuel'],
    deck: 'gas-station',
    textKind: 'outsider',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'addHelpless', count: 1 },
        { kind: 'adjustMorale', amount: 1 },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },

  /* ------------------------------------------------------------------ *
   * Library
   * ------------------------------------------------------------------ */
  {
    id: 'it-library-card-catalog',
    name: 'Card Catalog Drawer',
    text: 'Draw one card from the library deck.',
    symbols: ['education'],
    deck: 'library',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'drawItems',
      to: { kind: 'effectController' },
      deck: { kind: 'locationItems', location: 'library' },
      count: 1,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-reference-desk',
    name: 'Reference Desk Bell',
    text: 'Equipped survivor: once per round, draw one card from the library deck.',
    symbols: ['education', 'tool'],
    deck: 'library',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'reference-desk-search',
        text: 'Draw one card from the library deck.',
        location: 'library',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'drawItems',
          to: { kind: 'effectController' },
          deck: { kind: 'locationItems', location: 'library' },
          count: 1,
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-book-cart',
    name: 'Book Cart',
    text: 'Equipped survivor: once per round, remove up to two noise tokens from this location.',
    symbols: ['tool', 'education'],
    deck: 'library',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'book-cart-quiet',
        text: 'Remove up to two noise tokens from this location.',
        location: 'library',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: { kind: 'removeNoise', count: 2, location: { kind: 'sourceLocation' } },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-history-volume',
    name: 'History Volume',
    text: 'Move one survivor you control to the colony without rolling exposure; this does not use that survivor’s move.',
    symbols: ['education', 'survivor'],
    deck: 'library',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'moveSurvivor',
      target: {
        kind: 'chosen',
        by: { kind: 'effectController' },
        among: { kind: 'allControlledBy', player: { kind: 'effectController' } },
      },
      to: { kind: 'colony' },
      rollExposure: false,
      consumesMoveAllowance: false,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-microfilm-reel',
    name: 'Microfilm Reel',
    text: 'Draw two cards from the library deck, then discard one card from your hand.',
    symbols: ['education', 'tool'],
    deck: 'library',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'drawItems',
          to: { kind: 'effectController' },
          deck: { kind: 'locationItems', location: 'library' },
          count: 2,
        },
        { kind: 'discardItems', from: { kind: 'effectController' }, count: 1 },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-quiet-sign',
    name: 'Quiet Please Sign',
    text: 'Remove up to two noise tokens from the library.',
    symbols: ['tool', 'education'],
    deck: 'library',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: { kind: 'removeNoise', count: 2, location: { kind: 'fixed', location: 'library' } },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-archival-gloves',
    name: 'Archival Gloves',
    text: 'Equipped survivor: once per round, heal one wound from a survivor at this location, removing frostbite first.',
    symbols: ['medicine', 'tool'],
    deck: 'library',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'archival-gloves-care',
        text: 'Heal one wound from a survivor at this location, removing frostbite first.',
        location: 'library',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'heal',
          target: {
            kind: 'chosen',
            by: { kind: 'effectController' },
            among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
          },
          amount: 1,
          frostbiteFirst: true,
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-computer-terminal',
    name: 'Computer Terminal',
    text: 'Roll a die. On 4+, add two food to the colony; otherwise add one noise token at the library.',
    symbols: ['education', 'fuel'],
    deck: 'library',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'rollDie', sides: 6, store: 'terminal' },
        {
          kind: 'branch',
          test: { kind: 'variable', name: 'terminal', atLeast: 4 },
          then: { kind: 'adjustFood', amount: 2 },
          otherwise: { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'library' } },
        },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-circulation-list',
    name: 'Circulation List',
    text: 'Add one helpless survivor to the colony, if there is room, then lower morale by one.',
    symbols: ['education', 'survivor'],
    deck: 'library',
    textKind: 'outsider',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'addHelpless', count: 1 },
        { kind: 'adjustMorale', amount: -1 },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-map-case',
    name: 'Map Case',
    text: 'Equipped survivor: once per round, move this survivor to the colony without rolling exposure; this does not use their move.',
    symbols: ['education', 'tool'],
    deck: 'library',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'map-case-route',
        text: 'Move this survivor to the colony without rolling exposure; this does not use their move.',
        location: 'library',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'moveSurvivor',
          target: { kind: 'source' },
          to: { kind: 'colony' },
          rollExposure: false,
          consumesMoveAllowance: false,
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-childrens-corner',
    name: 'Children’s Corner Box',
    text: 'Add one food to the colony, then raise morale by one.',
    symbols: ['survivor', 'food'],
    deck: 'library',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'adjustFood', amount: 1 },
        { kind: 'adjustMorale', amount: 1 },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-community-board',
    name: 'Community Board',
    text: 'Add one noise token at every non-colony location, then add one food to the colony.',
    symbols: ['education', 'survivor'],
    deck: 'library',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'addNoise', count: 1, location: { kind: 'eachNonColony' } },
        { kind: 'adjustFood', amount: 1 },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-donation-box',
    name: 'Donation Box',
    text: 'If you can discard a food card, discard it to raise morale by two; otherwise lower morale by one.',
    symbols: ['food', 'survivor'],
    deck: 'library',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'branch',
      test: {
        kind: 'holdsCards',
        player: { kind: 'effectController' },
        requirement: { symbols: ['food'] },
        atLeast: 1,
      },
      then: {
        kind: 'sequence',
        effects: [
          {
            kind: 'discardItems',
            from: { kind: 'effectController' },
            count: 1,
            requirement: { symbols: ['food'] },
          },
          { kind: 'adjustMorale', amount: 2 },
        ],
      },
      otherwise: { kind: 'adjustMorale', amount: -1 },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-reading-lamp',
    name: 'Reading Lamp',
    text: 'Equipped survivor: once per round, remove up to two noise tokens from the library.',
    symbols: ['fuel', 'education'],
    deck: 'library',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'reading-lamp-quiet',
        text: 'Remove up to two noise tokens from the library.',
        location: 'library',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: { kind: 'removeNoise', count: 2, location: { kind: 'fixed', location: 'library' } },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-locked-stacks',
    name: 'Locked Stacks Key',
    text: 'Place one barricade at your location, then draw one card from the library deck.',
    symbols: ['tool', 'education'],
    deck: 'library',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'addBarricade', count: 1, location: { kind: 'sourceLocation' } },
        {
          kind: 'drawItems',
          to: { kind: 'effectController' },
          deck: { kind: 'locationItems', location: 'library' },
          count: 1,
        },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-staff-directory',
    name: 'Staff Directory',
    text: 'Take a random card from another player.',
    symbols: ['education', 'weapon'],
    deck: 'library',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'stealRandomCard',
      from: { kind: 'chosen', by: { kind: 'effectController' }, among: 'otherPlayers' },
      to: { kind: 'effectController' },
    },
    nonCooperative: true,
    matureContent: false,
  },
  {
    id: 'it-library-shelving-ladder',
    name: 'Shelving Ladder',
    text: 'Equipped survivor: once per round, place one barricade at this location.',
    symbols: ['tool', 'education'],
    deck: 'library',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'shelving-ladder-fortify',
        text: 'Place one barricade at this location.',
        location: 'library',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: { kind: 'addBarricade', count: 1, location: { kind: 'sourceLocation' } },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-fine-notice',
    name: 'Fine Notice',
    text: 'If able, discard one card from your hand. Then add one noise token at every non-colony location.',
    symbols: ['education', 'tool'],
    deck: 'library',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'ifAble', effect: { kind: 'discardItems', from: { kind: 'effectController' }, count: 1 } },
        { kind: 'addNoise', count: 1, location: { kind: 'eachNonColony' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-shelter-manual',
    name: 'Shelter Manual',
    text: 'If morale is three or lower, raise morale by two; otherwise add one food to the colony.',
    symbols: ['education', 'food'],
    deck: 'library',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'branch',
      test: { kind: 'morale', atMost: 3 },
      then: { kind: 'adjustMorale', amount: 2 },
      otherwise: { kind: 'adjustFood', amount: 1 },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-library-weather-almanac',
    name: 'Weather Almanac',
    text: 'If two or fewer rounds remain, add one food to the colony; otherwise add one round to the round tracker.',
    symbols: ['education', 'fuel'],
    deck: 'library',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'branch',
      test: { kind: 'roundsRemaining', atMost: 2 },
      then: { kind: 'adjustFood', amount: 1 },
      otherwise: { kind: 'adjustRounds', amount: 1 },
    },
    nonCooperative: false,
    matureContent: false,
  },

  /* ------------------------------------------------------------------ *
   * Hospital
   * ------------------------------------------------------------------ */
  {
    id: 'it-hospital-bandage-roll',
    name: 'Bandage Roll',
    text: 'Equipped survivor: once per round, heal one wound from a survivor at this location, removing frostbite first.',
    symbols: ['medicine'],
    deck: 'hospital',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'bandage-roll-care',
        text: 'Heal one wound from a survivor at this location, removing frostbite first.',
        location: 'hospital',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'heal',
          target: {
            kind: 'chosen',
            by: { kind: 'effectController' },
            among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
          },
          amount: 1,
          frostbiteFirst: true,
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-hospital-antibiotic-vial',
    name: 'Antibiotic Vial',
    text: 'Heal up to two wounds from one survivor at your location, removing frostbite first.',
    symbols: ['medicine'],
    deck: 'hospital',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'heal',
      target: {
        kind: 'chosen',
        by: { kind: 'effectController' },
        among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
      },
      amount: 2,
      frostbiteFirst: true,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-hospital-triage-chart',
    name: 'Triage Chart',
    text: 'Choose one: heal one wound from a survivor here, or add one helpless survivor to the colony.',
    symbols: ['medicine', 'survivor'],
    deck: 'hospital',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'choice',
      prompt: 'Triage Chart',
      chooser: { kind: 'effectController' },
      options: [
        {
          id: 'triage-heal',
          text: 'Heal one wound from a survivor here.',
          outcome: {
            kind: 'heal',
            target: {
              kind: 'chosen',
              by: { kind: 'effectController' },
              among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
            },
            amount: 1,
          },
        },
        {
          id: 'triage-arrival',
          text: 'Add one helpless survivor to the colony, if there is room.',
          outcome: { kind: 'addHelpless', count: 1 },
        },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-hospital-oxygen-tank',
    name: 'Oxygen Tank',
    text: 'Heal one wound from a survivor at your location, then remove one noise token from the hospital.',
    symbols: ['medicine', 'tool'],
    deck: 'hospital',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'heal',
          target: {
            kind: 'chosen',
            by: { kind: 'effectController' },
            among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
          },
          amount: 1,
        },
        { kind: 'removeNoise', count: 1, location: { kind: 'fixed', location: 'hospital' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-hospital-surgical-saw',
    name: 'Surgical Saw',
    text: 'Equipped survivor: once per round, kill up to one zombie here without rolling exposure, then wound this survivor.',
    symbols: ['weapon', 'medicine'],
    deck: 'hospital',
    textKind: 'event',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'surgical-saw-cut',
        text: 'Kill one zombie here without rolling exposure, then wound this survivor.',
        location: 'hospital',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'sequence',
          effects: [
            {
              kind: 'killZombies',
              count: 1,
              location: { kind: 'sourceLocation' },
              isAttack: false,
              rollExposure: false,
              killer: { kind: 'source' },
            },
            { kind: 'wound', target: { kind: 'source' }, amount: 1 },
          ],
        },
      },
    ],
    nonCooperative: false,
    matureContent: true,
  },
  {
    id: 'it-hospital-wheelchair',
    name: 'Wheelchair',
    text: 'Move one survivor you control to the colony without rolling exposure; this does not use that survivor’s move.',
    symbols: ['tool', 'survivor'],
    deck: 'hospital',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'moveSurvivor',
      target: {
        kind: 'chosen',
        by: { kind: 'effectController' },
        among: { kind: 'allControlledBy', player: { kind: 'effectController' } },
      },
      to: { kind: 'colony' },
      rollExposure: false,
      consumesMoveAllowance: false,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-hospital-ambulance-keys',
    name: 'Ambulance Keys',
    text: 'Move one survivor you control to the colony and roll exposure for that move; this does not use their move.',
    symbols: ['fuel', 'survivor'],
    deck: 'hospital',
    textKind: 'outsider',
    kind: 'oneShot',
    onPlay: {
      kind: 'moveSurvivor',
      target: {
        kind: 'chosen',
        by: { kind: 'effectController' },
        among: { kind: 'allControlledBy', player: { kind: 'effectController' } },
      },
      to: { kind: 'colony' },
      rollExposure: true,
      consumesMoveAllowance: false,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-hospital-pharmacy-inventory',
    name: 'Pharmacy Inventory',
    text: 'Draw one card from the hospital deck, then heal one wound from a survivor at your location.',
    symbols: ['medicine', 'education'],
    deck: 'hospital',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'drawItems',
          to: { kind: 'effectController' },
          deck: { kind: 'locationItems', location: 'hospital' },
          count: 1,
        },
        {
          kind: 'heal',
          target: {
            kind: 'chosen',
            by: { kind: 'effectController' },
            among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
          },
          amount: 1,
        },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-hospital-morgue-tag',
    name: 'Morgue Tag',
    text: 'Remove one zombie from your location, then lower morale by one. The removal is not a kill.',
    symbols: ['medicine', 'weapon'],
    deck: 'hospital',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'removeZombies', count: 1, location: { kind: 'sourceLocation' } },
        { kind: 'adjustMorale', amount: -1 },
      ],
    },
    nonCooperative: false,
    matureContent: true,
  },
  {
    id: 'it-hospital-cleaning-cart',
    name: 'Cleaning Cart',
    text: 'Equipped survivor: once per round, remove up to two noise tokens from this location, then place one barricade there.',
    symbols: ['tool', 'medicine'],
    deck: 'hospital',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'cleaning-cart-scrub',
        text: 'Remove up to two noise tokens from this location, then place one barricade there.',
        location: 'hospital',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'sequence',
          effects: [
            { kind: 'removeNoise', count: 2, location: { kind: 'sourceLocation' } },
            { kind: 'addBarricade', count: 1, location: { kind: 'sourceLocation' } },
          ],
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-hospital-patient-file',
    name: 'Patient File',
    text: 'Draw one card from the hospital deck, then add one noise token at your location.',
    symbols: ['education', 'medicine'],
    deck: 'hospital',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'drawItems',
          to: { kind: 'effectController' },
          deck: { kind: 'locationItems', location: 'hospital' },
          count: 1,
        },
        { kind: 'addNoise', count: 1, location: { kind: 'sourceLocation' } },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-hospital-blood-drive',
    name: 'Blood Drive Sign-Up',
    text: 'Add one helpless survivor to the colony, if there is room, then lower morale by one.',
    symbols: ['medicine', 'survivor'],
    deck: 'hospital',
    textKind: 'outsider',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'addHelpless', count: 1 },
        { kind: 'adjustMorale', amount: -1 },
      ],
    },
    nonCooperative: false,
    matureContent: true,
  },
  {
    id: 'it-hospital-defibrillator',
    name: 'Defibrillator',
    text: 'Roll a die. On 4+, heal up to two wounds from one survivor here; otherwise wound one survivor here.',
    symbols: ['medicine', 'tool'],
    deck: 'hospital',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        { kind: 'rollDie', sides: 6, store: 'defibrillator' },
        {
          kind: 'branch',
          test: { kind: 'variable', name: 'defibrillator', atLeast: 4 },
          then: {
            kind: 'heal',
            target: {
              kind: 'chosen',
              by: { kind: 'effectController' },
              among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
            },
            amount: 2,
            frostbiteFirst: true,
          },
          otherwise: {
            kind: 'wound',
            target: {
              kind: 'chosen',
              by: { kind: 'effectController' },
              among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
            },
            amount: 1,
          },
        },
      ],
    },
    nonCooperative: false,
    matureContent: true,
  },
  {
    id: 'it-hospital-emergency-generator',
    name: 'Emergency Generator',
    text: 'Equipped survivor: once per game, add one round to the round tracker, then add two noise tokens at the hospital.',
    symbols: ['fuel', 'tool'],
    deck: 'hospital',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'emergency-generator-start',
        text: 'Add one round to the round tracker, then add two noise tokens at the hospital.',
        location: 'hospital',
        dieThreshold: null,
        usage: 'oncePerGame',
        effect: {
          kind: 'sequence',
          effects: [
            { kind: 'adjustRounds', amount: 1 },
            { kind: 'addNoise', count: 2, location: { kind: 'fixed', location: 'hospital' } },
          ],
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-hospital-quiet-ward',
    name: 'Quiet Ward Sign',
    text: 'Heal one wound from every survivor at your location, removing frostbite first.',
    symbols: ['medicine', 'tool'],
    deck: 'hospital',
    textKind: 'normal',
    kind: 'oneShot',
    onPlay: {
      kind: 'heal',
      target: { kind: 'allAt', location: { kind: 'sourceLocation' } },
      amount: 1,
      frostbiteFirst: true,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-hospital-security-key',
    name: 'Security Key',
    text: 'Equipped survivor: once per round, either place one barricade at this location or remove one zombie there. The removal is not a kill.',
    symbols: ['tool', 'weapon'],
    deck: 'hospital',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'security-key-choice',
        text: 'Either place one barricade here or remove one zombie here. The removal is not a kill.',
        location: 'hospital',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'choice',
          prompt: 'Security Key',
          chooser: { kind: 'effectController' },
          options: [
            {
              id: 'security-barricade',
              text: 'Place one barricade at this location.',
              outcome: { kind: 'addBarricade', count: 1, location: { kind: 'sourceLocation' } },
            },
            {
              id: 'security-remove',
              text: 'Remove one zombie from this location. This is not a kill.',
              outcome: { kind: 'removeZombies', count: 1, location: { kind: 'sourceLocation' } },
            },
          ],
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-hospital-burner-phone',
    name: 'Burner Phone',
    text: 'Take a random card from another player, then draw one card from the hospital deck.',
    symbols: ['tool', 'medicine'],
    deck: 'hospital',
    textKind: 'event',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'stealRandomCard',
          from: { kind: 'chosen', by: { kind: 'effectController' }, among: 'otherPlayers' },
          to: { kind: 'effectController' },
        },
        {
          kind: 'drawItems',
          to: { kind: 'effectController' },
          deck: { kind: 'locationItems', location: 'hospital' },
          count: 1,
        },
      ],
    },
    nonCooperative: true,
    matureContent: false,
  },
  {
    id: 'it-hospital-discharge-papers',
    name: 'Discharge Papers',
    text: 'Move one survivor you control to the colony without rolling exposure; this does not use that survivor’s move, then raise morale by one.',
    symbols: ['survivor', 'education'],
    deck: 'hospital',
    textKind: 'outsider',
    kind: 'oneShot',
    onPlay: {
      kind: 'sequence',
      effects: [
        {
          kind: 'moveSurvivor',
          target: {
            kind: 'chosen',
            by: { kind: 'effectController' },
            among: { kind: 'allControlledBy', player: { kind: 'effectController' } },
          },
          to: { kind: 'colony' },
          rollExposure: false,
          consumesMoveAllowance: false,
        },
        { kind: 'adjustMorale', amount: 1 },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-hospital-doctors-notes',
    name: 'Doctor’s Notes',
    text: 'Equipped survivor: once per round, draw one card from the hospital deck, then add one noise token at the hospital.',
    symbols: ['education', 'medicine'],
    deck: 'hospital',
    textKind: 'normal',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'doctors-notes-rounds',
        text: 'Draw one card from the hospital deck, then add one noise token at the hospital.',
        location: 'hospital',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'sequence',
          effects: [
            {
              kind: 'drawItems',
              to: { kind: 'effectController' },
              deck: { kind: 'locationItems', location: 'hospital' },
              count: 1,
            },
            { kind: 'addNoise', count: 1, location: { kind: 'fixed', location: 'hospital' } },
          ],
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'it-hospital-visitor-badge',
    name: 'Visitor Badge',
    text: 'Equipped survivor: once per round, ask another player to give you a card to play immediately.',
    symbols: ['survivor', 'tool'],
    deck: 'hospital',
    textKind: 'outsider',
    kind: 'equip',
    equippedAbilities: [
      {
        id: 'visitor-badge-request',
        text: 'Ask another player to give you a card to play immediately.',
        location: 'hospital',
        dieThreshold: null,
        usage: 'oncePerRound',
        effect: {
          kind: 'requestCard',
          requester: { kind: 'effectController' },
          from: { kind: 'chosen', by: { kind: 'effectController' }, among: 'otherPlayers' },
        },
      },
    ],
    nonCooperative: false,
    matureContent: false,
  },
];
