/**
 * Original secret-objective catalog for the Dead of Winter base pack.
 *
 * These are authored records rather than the generated objective fixtures.
 * Hoarder keeps the §18.2 strict-most interpretation, and the exiled cards
 * make their reveal and replacement behavior explicit for §14.1.
 */

import type { SecretObjectiveDefinition } from '../schema.js';

const nonBetrayal: SecretObjectiveDefinition[] = [
  {
    id: 'so-hoarder',
    name: 'Hoarder',
    text: 'End the game holding strictly the most cards in hand.',
    kind: 'nonBetrayal',
    // §18.2: a tie for most cards is not enough.
    completion: { kind: 'strictlyMostCardsInHand', player: { kind: 'effectController' } },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-hunger',
    name: 'Hunger',
    text: 'End the game with at least three food cards in your hand or equipped.',
    kind: 'nonBetrayal',
    // §18.2: Hunger counts food cards, not food tokens.
    completion: {
      kind: 'holdsCards',
      player: { kind: 'effectController' },
      requirement: { symbols: ['food'] },
      atLeast: 3,
      includeEquipped: true,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-warm-hands',
    name: 'Warm Hands',
    text: 'End the game with at least three survivors under your command.',
    kind: 'nonBetrayal',
    completion: { kind: 'controlsSurvivors', player: { kind: 'effectController' }, atLeast: 3 },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-colony-wardens',
    name: 'Colony Wardens',
    text: "Keep at least two of your survivors inside the colony at game's end.",
    kind: 'nonBetrayal',
    completion: {
      kind: 'survivorsAt',
      location: { kind: 'colony' },
      controlledBy: { kind: 'effectController' },
      atLeast: 2,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-snowline-scouts',
    name: 'Snowline Scouts',
    text: 'Have at least two of your survivors stationed beyond the colony when the game ends.',
    kind: 'nonBetrayal',
    completion: {
      kind: 'survivorsAt',
      location: { kind: 'eachNonColony' },
      controlledBy: { kind: 'effectController' },
      atLeast: 2,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-single-shelter',
    name: 'Single Shelter',
    text: 'End the game with exactly one of your survivors at the colony.',
    kind: 'nonBetrayal',
    completion: {
      kind: 'survivorsAt',
      location: { kind: 'colony' },
      controlledBy: { kind: 'effectController' },
      atLeast: 1,
      atMost: 1,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-fuel-run',
    name: 'Fuel Runner',
    text: 'Finish with two fuel- or tool-symbol cards in hand or equipped.',
    kind: 'nonBetrayal',
    completion: {
      kind: 'holdsCards',
      player: { kind: 'effectController' },
      requirement: { symbols: ['fuel', 'tool'] },
      atLeast: 2,
      includeEquipped: true,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-classroom-keeper',
    name: 'Classroom Keeper',
    text: 'Finish with two education-symbol cards in hand or equipped.',
    kind: 'nonBetrayal',
    completion: {
      kind: 'holdsCards',
      player: { kind: 'effectController' },
      requirement: { symbols: ['education'] },
      atLeast: 2,
      includeEquipped: true,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-infirmary-steward',
    name: 'Infirmary Steward',
    text: 'Finish with two medicine-symbol cards in hand or equipped.',
    kind: 'nonBetrayal',
    completion: {
      kind: 'holdsCards',
      player: { kind: 'effectController' },
      requirement: { symbols: ['medicine'] },
      atLeast: 2,
      includeEquipped: true,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-armory-keeper',
    name: 'Armory Keeper',
    text: 'Finish with two weapon-symbol cards in hand or equipped.',
    kind: 'nonBetrayal',
    completion: {
      kind: 'holdsCards',
      player: { kind: 'effectController' },
      requirement: { symbols: ['weapon'] },
      atLeast: 2,
      includeEquipped: true,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-salvage-ledger',
    name: 'Salvage Ledger',
    text: 'Hold three non-starter cards, counting equipped cards.',
    kind: 'nonBetrayal',
    completion: {
      kind: 'holdsCards',
      player: { kind: 'effectController' },
      requirement: { excludeStarter: true },
      atLeast: 3,
      includeEquipped: true,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-public-reserve',
    name: 'Public Reserve',
    text: 'See at least two survivor-symbol cards added to the main objective.',
    kind: 'nonBetrayal',
    completion: {
      kind: 'objectiveContributions',
      requirement: { symbols: ['survivor'] },
      atLeast: 2,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-high-morale',
    name: 'High Morale',
    text: 'End the game with morale at four or higher.',
    kind: 'nonBetrayal',
    completion: { kind: 'morale', atLeast: 4 },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-last-watch',
    name: 'Last Watch',
    text: 'End the game with at least two rounds still on the tracker.',
    kind: 'nonBetrayal',
    completion: { kind: 'roundsRemaining', atLeast: 2 },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-full-pantry',
    name: 'Full Pantry',
    text: 'Leave at least four food tokens in the colony stores.',
    kind: 'nonBetrayal',
    completion: { kind: 'food', atLeast: 4 },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-clean-slate',
    name: 'Clean Slate',
    text: 'Finish with no more than eight cards in the waste pile.',
    kind: 'nonBetrayal',
    completion: { kind: 'wasteCount', atMost: 8 },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-ration-survivor',
    name: 'Ration Survivor',
    text: 'End the game without a starvation token in the food supply.',
    kind: 'nonBetrayal',
    completion: { kind: 'not', of: { kind: 'starvationTokens', atLeast: 1 } },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-quiet-gates',
    name: 'Quiet Gates',
    text: 'Leave no more than two zombies at the colony.',
    kind: 'nonBetrayal',
    completion: { kind: 'zombiesAt', location: { kind: 'colony' }, atMost: 2 },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-frozen-outposts',
    name: 'Frozen Outposts',
    text: 'Leave no more than four zombies across all non-colony locations.',
    kind: 'nonBetrayal',
    completion: { kind: 'zombiesAt', location: { kind: 'eachNonColony' }, atMost: 4 },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-helpless-free',
    name: 'Helpless Free',
    text: 'End the game with no helpless survivors at the colony.',
    kind: 'nonBetrayal',
    completion: { kind: 'helplessSurvivors', atMost: 0 },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-open-bunk',
    name: 'Open Bunk',
    text: 'End the game while at least one colony survivor space is empty.',
    kind: 'nonBetrayal',
    completion: { kind: 'colonyHasEmptySurvivorSpace' },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-barricade-ring',
    name: 'Barricade Ring',
    text: 'End the game with at least two standing barricades at the colony.',
    kind: 'nonBetrayal',
    completion: { kind: 'barricadesAt', location: { kind: 'colony' }, atLeast: 2 },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-ready-team',
    name: 'Ready Team',
    text: 'End with two survivors under your command and at least one fuel card in hand or equipped.',
    kind: 'nonBetrayal',
    completion: {
      kind: 'all',
      of: [
        { kind: 'controlsSurvivors', player: { kind: 'effectController' }, atLeast: 2 },
        {
          kind: 'holdsCards',
          player: { kind: 'effectController' },
          requirement: { symbols: ['fuel'] },
          atLeast: 1,
          includeEquipped: true,
        },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-two-fronts',
    name: 'Two Fronts',
    text: 'Finish with either five food tokens in the colony stores or three colony barricades.',
    kind: 'nonBetrayal',
    completion: {
      kind: 'any',
      of: [
        { kind: 'food', atLeast: 5 },
        { kind: 'barricadesAt', location: { kind: 'colony' }, atLeast: 3 },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
];

const betrayal: SecretObjectiveDefinition[] = [
  {
    id: 'so-fractured-walls',
    name: 'Fractured Walls',
    text: "End the game after the colony's morale reaches zero.",
    kind: 'betrayal',
    completion: { kind: 'morale', atMost: 0 },
    nonCooperative: true,
    // Mature classification: this objective explicitly pursues the colony's collapse.
    matureContent: true,
  },
  {
    id: 'so-empty-pantry',
    name: 'Empty Pantry',
    text: 'End the game with no food tokens in the colony stores.',
    kind: 'betrayal',
    completion: { kind: 'food', atMost: 0 },
    nonCooperative: true,
    matureContent: false,
  },
  {
    id: 'so-winter-clock',
    name: 'Winter Clock',
    text: 'Let the round tracker reach zero before the game ends.',
    kind: 'betrayal',
    completion: { kind: 'roundsRemaining', atMost: 0 },
    nonCooperative: true,
    matureContent: false,
  },
  {
    id: 'so-unquiet-colony',
    name: 'Unquiet Colony',
    text: 'End with at least four zombies inside the colony.',
    kind: 'betrayal',
    completion: { kind: 'zombiesAt', location: { kind: 'colony' }, atLeast: 4 },
    nonCooperative: true,
    matureContent: false,
  },
  {
    id: 'so-open-gate',
    name: 'Open Gate',
    text: 'Leave at least six zombies across the non-colony locations.',
    kind: 'betrayal',
    completion: { kind: 'zombiesAt', location: { kind: 'eachNonColony' }, atLeast: 6 },
    nonCooperative: true,
    // Mature classification: this objective deliberately leaves multiple outposts overrun.
    matureContent: true,
  },
  {
    id: 'so-no-safe-haven',
    name: 'No Safe Haven',
    text: 'End with at least three helpless survivors at the colony.',
    kind: 'betrayal',
    completion: { kind: 'helplessSurvivors', atLeast: 3 },
    nonCooperative: true,
    // Mature classification: this objective centers on abandoning helpless survivors.
    matureContent: true,
  },
  {
    id: 'so-burned-supplies',
    name: 'Burned Supplies',
    text: 'End the game with at least twelve cards in the waste pile.',
    kind: 'betrayal',
    completion: { kind: 'wasteCount', atLeast: 12 },
    nonCooperative: true,
    matureContent: false,
  },
  {
    id: 'so-broken-ring',
    name: 'Broken Ring',
    text: 'End the game with no barricade standing at the colony.',
    kind: 'betrayal',
    completion: {
      kind: 'not',
      of: { kind: 'barricadesAt', location: { kind: 'colony' }, atLeast: 1 },
    },
    nonCooperative: true,
    matureContent: false,
  },
  {
    id: 'so-lone-dissenter',
    name: 'Lone Dissenter',
    text: 'End the game with at most one survivor under your command.',
    kind: 'betrayal',
    completion: { kind: 'controlsSurvivors', player: { kind: 'effectController' }, atMost: 1 },
    nonCooperative: true,
    matureContent: false,
  },
  {
    id: 'so-final-crack',
    name: 'Final Crack',
    text: 'End with morale at one or less, or at least five zombies at the colony.',
    kind: 'betrayal',
    completion: {
      kind: 'any',
      of: [
        { kind: 'morale', atMost: 1 },
        { kind: 'zombiesAt', location: { kind: 'colony' }, atLeast: 5 },
      ],
    },
    nonCooperative: true,
    matureContent: false,
  },
];

const exiled: SecretObjectiveDefinition[] = [
  {
    id: 'so-exile-outpost',
    name: 'Outpost Refuge',
    text: 'Reveal any non-betrayal original objective, then end with at least one of your survivors outside the colony.',
    kind: 'exiled',
    revealsOriginalObjective: true,
    completion: {
      kind: 'survivorsAt',
      location: { kind: 'eachNonColony' },
      controlledBy: { kind: 'effectController' },
      atLeast: 1,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-exile-two-fronts',
    name: 'Exile Two Fronts',
    text: 'Reveal any non-betrayal original objective, then end with at least two of your survivors beyond the colony.',
    kind: 'exiled',
    revealsOriginalObjective: true,
    completion: {
      kind: 'survivorsAt',
      location: { kind: 'eachNonColony' },
      controlledBy: { kind: 'effectController' },
      atLeast: 2,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-exile-schoolhouse',
    name: 'Schoolhouse Refuge',
    text: 'Reveal any non-betrayal original objective, then end with one of your survivors at the school.',
    kind: 'exiled',
    revealsOriginalObjective: true,
    completion: {
      kind: 'survivorsAt',
      location: { kind: 'fixed', location: 'school' },
      controlledBy: { kind: 'effectController' },
      atLeast: 1,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-exile-infirmary',
    name: 'Infirmary Refuge',
    text: 'Reveal any non-betrayal original objective, then end with one of your survivors at the hospital.',
    kind: 'exiled',
    revealsOriginalObjective: true,
    completion: {
      kind: 'survivorsAt',
      location: { kind: 'fixed', location: 'hospital' },
      controlledBy: { kind: 'effectController' },
      atLeast: 1,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-exile-supply-cache',
    name: 'Exiled Supply Cache',
    text: 'Reveal any non-betrayal original objective, then end holding at least one food card in hand or equipped.',
    kind: 'exiled',
    revealsOriginalObjective: true,
    completion: {
      kind: 'holdsCards',
      player: { kind: 'effectController' },
      requirement: { symbols: ['food'] },
      atLeast: 1,
      includeEquipped: true,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-exile-tool-belt',
    name: 'Exiled Tool Belt',
    text: 'Reveal any non-betrayal original objective, then replace it with this task: finish with a tool card in hand or equipped.',
    kind: 'exiled',
    revealsOriginalObjective: true,
    replacesOriginalObjective: true,
    completion: {
      kind: 'holdsCards',
      player: { kind: 'effectController' },
      requirement: { symbols: ['tool'] },
      atLeast: 1,
      includeEquipped: true,
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-exile-cold-watch',
    name: 'Exiled Cold Watch',
    text: 'Reveal any non-betrayal original objective, then replace it with this task: finish with morale at three or higher.',
    kind: 'exiled',
    revealsOriginalObjective: true,
    replacesOriginalObjective: true,
    completion: { kind: 'morale', atLeast: 3 },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-exile-empty-road',
    name: 'Empty Road',
    text: 'Reveal any non-betrayal original objective, then end with no more than three zombies across the outposts.',
    kind: 'exiled',
    revealsOriginalObjective: true,
    completion: { kind: 'zombiesAt', location: { kind: 'eachNonColony' }, atMost: 3 },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-exile-last-barricade',
    name: 'Last Barricade',
    text: 'Reveal any non-betrayal original objective, then replace it with this task: finish with a colony barricade.',
    kind: 'exiled',
    revealsOriginalObjective: true,
    replacesOriginalObjective: true,
    completion: { kind: 'barricadesAt', location: { kind: 'colony' }, atLeast: 1 },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'so-exile-lone-shelter',
    name: 'Lone Shelter',
    text: 'Reveal any non-betrayal original objective, then end with a survivor outside and none of yours at the colony.',
    kind: 'exiled',
    revealsOriginalObjective: true,
    completion: {
      kind: 'all',
      of: [
        { kind: 'controlsSurvivors', player: { kind: 'effectController' }, atLeast: 1 },
        {
          kind: 'survivorsAt',
          location: { kind: 'colony' },
          controlledBy: { kind: 'effectController' },
          atMost: 0,
        },
      ],
    },
    nonCooperative: false,
    matureContent: false,
  },
];

/** The complete authored secret-objective family: 24 / 10 / 10. */
export const BASE_SECRET_OBJECTIVES: SecretObjectiveDefinition[] = [
  ...nonBetrayal,
  ...betrayal,
  ...exiled,
];
