/**
 * The authored survivor catalog for dow-base.
 *
 * The six §18 survivor records are intentionally copied from the engine
 * fixture: those ids, names, and effects are regression-test identities. The
 * remaining cards keep the named roster and printed stat shape used by the
 * client art, but their abilities are original data for this development
 * catalog. Every ability is an effect tree understood by the §17 runner.
 */

import type { SurvivorCardDefinition } from '../schema.js';

export const BASE_SURVIVORS: SurvivorCardDefinition[] = [
  /* ------------------------------------------------------------------ *
   * §18 named survivor records — keep these definitions in lockstep with
   * testPack.ts. The regression suite uses their ids and behavior directly.
   * ------------------------------------------------------------------ */

  {
    id: 'sv-loretta-clay',
    name: 'Loretta Clay',
    occupation: 'Cook',
    influence: 3,
    attackThreshold: 4,
    searchThreshold: 4,
    // §18.1 errata: the threshold is `4+`, not exactly 4. `dieThreshold` is a
    // minimum everywhere in this engine, so encoding 4 here *is* "4 or better".
    ability: {
      id: 'loretta-fix',
      text: 'Spend a 4+ die at the colony to add one barricade.',
      location: 'colony',
      dieThreshold: 4,
      usage: 'unlimited',
      effect: { kind: 'addBarricade', count: 1, location: { kind: 'colony' } },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-edward-white',
    name: 'Edward White',
    occupation: 'Chemist',
    influence: 4,
    attackThreshold: 3,
    searchThreshold: 5,
    // §18.3: a second qualifying die plus a medicine card kills two *extra*
    // zombies with no exposure rolls at all. It is not a standalone action.
    ability: {
      id: 'edward-clear',
      text: 'Spend a 3+ die and discard a medicine card: kill two zombies here, skipping exposure.',
      location: 'ANYWHERE',
      dieThreshold: 3,
      usage: 'unlimited',
      effect: {
        kind: 'sequence',
        effects: [
          {
            kind: 'discardItems',
            from: { kind: 'effectController' },
            count: 1,
            requirement: { symbols: ['medicine'] },
          },
          {
            kind: 'killZombies',
            count: 2,
            location: { kind: 'sourceLocation' },
            isAttack: false,
            rollExposure: false,
            killer: { kind: 'source' },
          },
        ],
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-john-price',
    name: 'John Price',
    occupation: 'Student',
    influence: 2,
    attackThreshold: 5,
    searchThreshold: 3,
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-forest-plum',
    name: 'Forest Plum',
    occupation: 'Mall Santa',
    influence: 1,
    attackThreshold: 5,
    searchThreshold: 4,
    // §18.3: a self-naming ability copied by John Price names *John*.
    ability: {
      id: 'forest-sacrifice',
      text: 'Remove Forest Plum from the game to remove three zombies here.',
      location: 'ANYWHERE',
      dieThreshold: null,
      usage: 'oncePerGame',
      effect: {
        kind: 'sequence',
        effects: [
          { kind: 'removeZombies', count: 3, location: { kind: 'sourceLocation' } },
          // `remove`, not `kill`: §9.3 costs no morale and §7.1 satisfies no
          // kill-based objective.
          { kind: 'removeSurvivor', target: { kind: 'source' } },
        ],
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-buddy-davis',
    name: 'Buddy Davis',
    occupation: 'Fitness Trainer',
    influence: 3,
    attackThreshold: 4,
    searchThreshold: 4,
    ability: {
      id: 'buddy-heal',
      text: 'Once per round, heal one wound from a survivor at your location.',
      location: 'ANYWHERE',
      dieThreshold: null,
      usage: 'oncePerRound',
      effect: {
        kind: 'heal',
        target: {
          kind: 'chosen',
          by: { kind: 'effectController' },
          among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
        },
        amount: 1,
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-bev-russell',
    name: 'Bev Russell',
    occupation: 'Mother',
    influence: 0,
    attackThreshold: 6,
    searchThreshold: 6,
    // §18.4: counts for zombie-generation totals while present, but "cannot be
    // selected as an overrun casualty because she cannot be killed".
    cannotBeKilled: true,
    nonCooperative: true,
    matureContent: false,
  },

  /* ------------------------------------------------------------------ *
   * Original ability-bearing survivors. The roster names and stat values
   * remain stable so existing art and setup fixtures retain their identities.
   * ------------------------------------------------------------------ */

  {
    id: 'sv-alexis-grey',
    name: 'Alexis Grey',
    occupation: 'Librarian',
    influence: 46,
    attackThreshold: 5,
    searchThreshold: 4,
    ability: {
      id: 'alexis-index',
      text: 'At the library, once per turn, draw one library card.',
      location: 'library',
      dieThreshold: null,
      usage: 'oncePerTurn',
      effect: {
        kind: 'drawItems',
        to: { kind: 'effectController' },
        deck: { kind: 'locationItems', location: 'library' },
        count: 1,
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-andrew-evans',
    name: 'Andrew Evans',
    occupation: 'Farmer',
    influence: 12,
    attackThreshold: 3,
    searchThreshold: 3,
    ability: {
      id: 'andrew-ration',
      text: 'At the grocery store, once per round, add one food to the colony.',
      location: 'grocery-store',
      dieThreshold: null,
      usage: 'oncePerRound',
      effect: { kind: 'adjustFood', amount: 1 },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-annaleigh-chan',
    name: 'Annaleigh Chan',
    occupation: 'Lawyer',
    influence: 38,
    attackThreshold: 2,
    searchThreshold: 2,
    ability: {
      id: 'annaleigh-bargain',
      text: 'At the colony, once per game, draw one library card at the cost of one morale.',
      location: 'colony',
      dieThreshold: null,
      usage: 'oncePerGame',
      effect: {
        kind: 'sequence',
        effects: [
          {
            kind: 'drawItems',
            to: { kind: 'effectController' },
            deck: { kind: 'locationItems', location: 'library' },
            count: 1,
          },
          { kind: 'adjustMorale', amount: -1 },
        ],
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-arthur-thurston',
    name: 'Arthur Thurston',
    occupation: 'Principal',
    influence: 68,
    attackThreshold: 4,
    searchThreshold: 2,
    ability: {
      id: 'arthur-lockdown',
      text: 'Spend a 4+ die to place one barricade at your location.',
      location: 'ANYWHERE',
      dieThreshold: 4,
      usage: 'oncePerRound',
      effect: { kind: 'addBarricade', count: 1, location: { kind: 'sourceLocation' } },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-ashley-ross',
    name: 'Ashley Ross',
    occupation: 'Construction Worker',
    influence: 52,
    attackThreshold: 2,
    searchThreshold: 5,
    ability: {
      id: 'ashley-clearance',
      text: 'At the police station, once per turn, remove up to two noise there.',
      location: 'police-station',
      dieThreshold: null,
      usage: 'oncePerTurn',
      effect: { kind: 'removeNoise', count: 2, location: { kind: 'sourceLocation' } },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-brandon-kane',
    name: 'Brandon Kane',
    occupation: 'Janitor',
    influence: 12,
    attackThreshold: 2,
    searchThreshold: 4,
    ability: {
      id: 'brandon-sweep',
      text: 'At the gas station, spend a 3+ die to draw one gas-station card.',
      location: 'gas-station',
      dieThreshold: 3,
      usage: 'oncePerRound',
      effect: {
        kind: 'drawItems',
        to: { kind: 'effectController' },
        deck: { kind: 'locationItems', location: 'gas-station' },
        count: 1,
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-brian-lee',
    name: 'Brian Lee',
    occupation: 'Mayor',
    influence: 68,
    attackThreshold: 3,
    searchThreshold: 4,
    ability: {
      id: 'brian-rally',
      text: 'At the colony, once per round, raise morale by one.',
      location: 'colony',
      dieThreshold: null,
      usage: 'oncePerRound',
      effect: { kind: 'adjustMorale', amount: 1 },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-carla-thompson',
    name: 'Carla Thompson',
    occupation: 'Police Dispatcher',
    influence: 22,
    attackThreshold: 4,
    searchThreshold: 2,
    ability: {
      id: 'carla-precision',
      text: 'At the police station, spend a 4+ die to kill one zombie without exposure.',
      location: 'police-station',
      dieThreshold: 4,
      usage: 'oncePerGame',
      effect: {
        kind: 'killZombies',
        count: 1,
        location: { kind: 'sourceLocation' },
        isAttack: false,
        rollExposure: false,
        killer: { kind: 'source' },
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-daniel-smith',
    name: 'Daniel Smith',
    occupation: 'Sheriff',
    influence: 66,
    attackThreshold: 2,
    searchThreshold: 5,
    ability: {
      id: 'daniel-field-kit',
      text: 'At the hospital, once per round, discard a medicine card to heal two wounds here.',
      location: 'hospital',
      dieThreshold: null,
      usage: 'oncePerRound',
      effect: {
        kind: 'sequence',
        effects: [
          {
            kind: 'discardItems',
            from: { kind: 'effectController' },
            count: 1,
            requirement: { symbols: ['medicine'] },
          },
          {
            kind: 'heal',
            target: {
              kind: 'chosen',
              by: { kind: 'effectController' },
              among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
            },
            amount: 2,
          },
        ],
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-david-garcia',
    name: 'David Garcia',
    occupation: 'Accountant',
    influence: 50,
    attackThreshold: 4,
    searchThreshold: 3,
    ability: {
      id: 'david-inventory',
      text: 'At the police station, once per game, place a barricade and remove one noise there.',
      location: 'police-station',
      dieThreshold: null,
      usage: 'oncePerGame',
      effect: {
        kind: 'sequence',
        effects: [
          { kind: 'addBarricade', count: 1, location: { kind: 'sourceLocation' } },
          { kind: 'removeNoise', count: 1, location: { kind: 'sourceLocation' } },
        ],
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-gabriel-diaz',
    name: 'Gabriel Diaz',
    occupation: 'Fireman',
    influence: 60,
    attackThreshold: 2,
    searchThreshold: 3,
    ability: {
      id: 'gabriel-hotline',
      text: 'At the gas station, once per game, remove one zombie and add one noise there.',
      location: 'gas-station',
      dieThreshold: null,
      usage: 'oncePerGame',
      effect: {
        kind: 'sequence',
        effects: [
          { kind: 'removeZombies', count: 1, location: { kind: 'sourceLocation' } },
          { kind: 'addNoise', count: 1, location: { kind: 'sourceLocation' } },
        ],
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-gray-beard',
    name: 'Gray Beard',
    occupation: 'Pirate',
    influence: 16,
    attackThreshold: 1,
    searchThreshold: 4,
    ability: {
      id: 'gray-beard-broadside',
      text: 'Spend a 5+ die to remove two zombies at your location.',
      location: 'ANYWHERE',
      dieThreshold: 5,
      usage: 'oncePerGame',
      effect: { kind: 'removeZombies', count: 2, location: { kind: 'sourceLocation' } },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-harman-brooks',
    name: 'Harman Brooks',
    occupation: 'Park Ranger',
    influence: 32,
    attackThreshold: 3,
    searchThreshold: 3,
    ability: {
      id: 'harman-evacuation',
      text: 'Once per round, move one survivor at your location to the colony without exposure.',
      location: 'ANYWHERE',
      dieThreshold: null,
      usage: 'oncePerRound',
      effect: {
        kind: 'moveSurvivor',
        target: {
          kind: 'chosen',
          by: { kind: 'effectController' },
          among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
        },
        to: { kind: 'colony' },
        rollExposure: false,
        consumesMoveAllowance: false,
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-james-meyers',
    name: 'James Meyers',
    occupation: 'Psychiatrist',
    influence: 54,
    attackThreshold: 6,
    searchThreshold: 3,
    ability: {
      id: 'james-grounding',
      text: 'At the hospital, once per game, heal one wound here and remove one noise there.',
      location: 'hospital',
      dieThreshold: null,
      usage: 'oncePerGame',
      effect: {
        kind: 'sequence',
        effects: [
          {
            kind: 'heal',
            target: {
              kind: 'chosen',
              by: { kind: 'effectController' },
              among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
            },
            amount: 1,
          },
          { kind: 'removeNoise', count: 1, location: { kind: 'sourceLocation' } },
        ],
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-janet-taylor',
    name: 'Janet Taylor',
    occupation: 'Nurse',
    influence: 42,
    attackThreshold: 3,
    searchThreshold: 4,
    ability: {
      id: 'janet-supply-cart',
      text: 'At the hospital, once per turn, draw one hospital card and add one noise there.',
      location: 'hospital',
      dieThreshold: null,
      usage: 'oncePerTurn',
      effect: {
        kind: 'sequence',
        effects: [
          {
            kind: 'drawItems',
            to: { kind: 'effectController' },
            deck: { kind: 'locationItems', location: 'hospital' },
            count: 1,
          },
          { kind: 'addNoise', count: 1, location: { kind: 'sourceLocation' } },
        ],
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-jenny-clark',
    name: 'Jenny Clark',
    occupation: 'Waitress',
    influence: 24,
    attackThreshold: 4,
    searchThreshold: 3,
    ability: {
      id: 'jenny-leftovers',
      text: 'At the grocery store, once per game, add one food and one noise there.',
      location: 'grocery-store',
      dieThreshold: null,
      usage: 'oncePerGame',
      effect: {
        kind: 'sequence',
        effects: [
          { kind: 'adjustFood', amount: 1 },
          { kind: 'addNoise', count: 1, location: { kind: 'sourceLocation' } },
        ],
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-maria-lopez',
    name: 'Maria Lopez',
    occupation: 'Teacher',
    influence: 48,
    attackThreshold: 4,
    searchThreshold: 2,
    ability: {
      id: 'maria-lesson-plan',
      text: 'At the school, once per round, draw one school card and lower morale by one.',
      location: 'school',
      dieThreshold: null,
      usage: 'oncePerRound',
      effect: {
        kind: 'sequence',
        effects: [
          {
            kind: 'drawItems',
            to: { kind: 'effectController' },
            deck: { kind: 'locationItems', location: 'school' },
            count: 1,
          },
          { kind: 'adjustMorale', amount: -1 },
        ],
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-mike-cho',
    name: 'Mike Cho',
    occupation: 'Ninja',
    influence: 30,
    attackThreshold: 2,
    searchThreshold: 4,
    ability: {
      id: 'mike-ambush',
      text: 'At the police station, once per round, kill one zombie and roll exposure for it.',
      location: 'police-station',
      dieThreshold: 5,
      usage: 'oncePerRound',
      effect: {
        kind: 'killZombies',
        count: 1,
        location: { kind: 'sourceLocation' },
        isAttack: false,
        rollExposure: true,
        killer: { kind: 'source' },
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-olivia-brown',
    name: 'Olivia Brown',
    occupation: 'Doctor',
    influence: 56,
    attackThreshold: 4,
    searchThreshold: 3,
    ability: {
      id: 'olivia-triage',
      text: 'At the hospital, spend a 3+ die once per turn to heal a frostbite before a wound.',
      location: 'hospital',
      dieThreshold: 3,
      usage: 'oncePerTurn',
      effect: {
        kind: 'heal',
        target: {
          kind: 'chosen',
          by: { kind: 'effectController' },
          among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
        },
        amount: 1,
        frostbiteFirst: true,
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-rod-miller',
    name: 'Rod Miller',
    occupation: 'Truck Driver',
    influence: 40,
    attackThreshold: 3,
    searchThreshold: 3,
    ability: {
      id: 'rod-shuttle',
      text: 'Once per round, move one survivor at your location to the colony and roll exposure.',
      location: 'ANYWHERE',
      dieThreshold: 4,
      usage: 'oncePerRound',
      effect: {
        kind: 'moveSurvivor',
        target: {
          kind: 'chosen',
          by: { kind: 'effectController' },
          among: { kind: 'allAt', location: { kind: 'sourceLocation' } },
        },
        to: { kind: 'colony' },
        rollExposure: true,
        consumesMoveAllowance: false,
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-sophie-robinson',
    name: 'Sophie Robinson',
    occupation: 'Pilot',
    influence: 58,
    attackThreshold: 4,
    searchThreshold: 1,
    ability: {
      id: 'sophie-scout',
      text: 'Spend a 2+ die to remove one zombie at your location.',
      location: 'ANYWHERE',
      dieThreshold: 2,
      usage: 'oncePerRound',
      effect: { kind: 'removeZombies', count: 1, location: { kind: 'sourceLocation' } },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-sparky',
    name: 'Sparky',
    occupation: 'Stunt Dog',
    influence: 10,
    attackThreshold: 2,
    searchThreshold: 2,
    ability: {
      id: 'sparky-sniff',
      text: 'At the school, once per turn, add one noise there to draw one school card.',
      location: 'school',
      dieThreshold: null,
      usage: 'oncePerTurn',
      effect: {
        kind: 'sequence',
        effects: [
          { kind: 'addNoise', count: 1, location: { kind: 'sourceLocation' } },
          {
            kind: 'drawItems',
            to: { kind: 'effectController' },
            deck: { kind: 'sourceLocationItems' },
            count: 1,
          },
        ],
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-talia-jones',
    name: 'Talia Jones',
    occupation: 'Fortune Teller',
    influence: 28,
    attackThreshold: 3,
    searchThreshold: 1,
    ability: {
      id: 'talia-reading',
      text: 'At the colony, once per round, choose: raise morale by one or add one food.',
      location: 'colony',
      dieThreshold: null,
      usage: 'oncePerRound',
      effect: {
        kind: 'choice',
        prompt: 'Choose the colony reading.',
        chooser: { kind: 'effectController' },
        options: [
          {
            id: 'hope',
            text: 'Raise morale by one.',
            outcome: { kind: 'adjustMorale', amount: 1 },
          },
          {
            id: 'stores',
            text: 'Add one food to the colony.',
            outcome: { kind: 'adjustFood', amount: 1 },
          },
        ],
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
  {
    id: 'sv-thomas-heart',
    name: 'Thomas Heart',
    occupation: 'Soldier',
    influence: 64,
    attackThreshold: 1,
    searchThreshold: 3,
    ability: {
      id: 'thomas-volley',
      text: 'Spend a 6 die to kill three zombies at your location, rolling exposure for each.',
      location: 'ANYWHERE',
      dieThreshold: 6,
      usage: 'oncePerGame',
      effect: {
        kind: 'killZombies',
        count: 3,
        location: { kind: 'sourceLocation' },
        isAttack: false,
        rollExposure: true,
        killer: { kind: 'source' },
      },
    },
    nonCooperative: false,
    matureContent: false,
  },
];
