/** Mechanics briefing for the implemented game, not a strategy or move ranking.
 * Keep aligned with auction, building, bureaucracy, steps, endgame and trust.
 */
export const JEV_RULES = {
  objective: 'After every player finishes the combined build-and-power turn, reaching the supplied endGameCityThreshold ends the game. The winner can supply the most connected cities with owned plants and stored fuel, capped by network size; remaining money breaks ties. The triggering player need not win. There is no final income payment or fuel consumption: final evaluation computes feasible supply independently of the locked production choices. The Trust cannot win or trigger city thresholds.',
  order: 'Rounds proceed through player order, plant auctions, resource buying, combined building and production selection, then automatic settlement. Order ranks connected cities descending, then highest owned plant descending. Auctions follow that order; resources and building use reverse order. First-round auctions use the initial order, then order is recalculated before resources. The Trust stays second.',
  auction: 'Each player buys at most one plant per round. In round one every non-Trust player must buy; in later rounds passing nomination exits the auction phase. Passing on another player\'s auction only exits that auction. Only current-market plants can be nominated. The minimum is the printed number except a discounted plant costs at least 1. A lone eligible buyer pays the minimum. Buying a fourth plant requires scrapping an older plant, never the newly bought one; compatible fuel transfers subject to storage capacity and excess is lost.',
  sealedAuctionHouseRule: 'Nominator and other eligible bidders commit sealed minimum and maximum amounts or pass. Once all commit, the server simulates a clockwise auction starting at the nominator\'s minimum. Each challenger bids max(their minimum, current price + 1), or permanently drops out if that exceeds their maximum. The last bidder pays the final simulated price, not automatically their maximum. Clockwise order matters in ties. Other commitments are hidden. Cash used for the plant is no longer available for resources or connections.',
  resources: 'Buy in reverse player order from the cheapest available market spaces, paying per token. Submit a complete basket with buyResourcesAndFinish; it ends the resource turn, including in older saved games. Passing buys nothing. Combined purchases must fit cash and compatible storage across all owned plants. Storage is twice printed fuel per plant; hybrids share that capacity between coal and oil. Fuel can be reassigned among compatible plants. A plant requires exactly its printed fuel to run once per round; ecological plants need none. Partial fueling cannot run a plant. Extra stored fuel does not increase its printed output.',
  building: 'Build in reverse player order. A first network city costs its open slot with no connection charge. Further cities cost their lowest open slot plus the cheapest route from any city already in your network, including cities built this turn. Routes can pass through occupied cities and cities you do not own, but cannot leave the selected zone. Route costs are charged anew per city. A player may own only one slot per city and only one half of a metropolis. Slots cost 10, 15, 20; Steps 1, 2, 3 open one, two, three slots respectively. You may build repeatedly while cash and houses permit, or pass. Building itself neither buys fuel nor produces money.',
  combinedTurnHouseRule: 'Each player builds, then locks a production choice before the next player builds. Fuel consumption and income are deferred until ALL players finish those combined turns. Income from this round cannot fund building in the same round. If the game ends, locked production choices are discarded and feasible final supply is evaluated instead. Otherwise selected plants consume their full fuel, even if fewer cities are supplied, and income follows incomeByCitiesSupplied (index is cities supplied, capped at the last entry). Zero supplied cities earns 10. Output beyond connected cities has no payout.',
  settlement: 'After a normal round\'s production, refill resources using map, player count and Step. Refill highest-priced empty spaces first, limited by supply reserves. In Steps 1 and 2, put the highest future plant under the deck and draw a replacement. In Step 3 remove the lowest current plant and draw a replacement. With an exhausted deck remove the lowest market plant without replacement.',
  market: 'In Steps 1 and 2 the four lowest market plants are current and higher plants are future; re-sort after replacements. Step 3 has six current plants and no future market. At the auction phase start the lowest current plant receives a discount. While the discount replacement rule is armed, a lower-numbered replacement is discarded with the discount, then another is drawn. An unsold discounted plant is removed and replaced at auction phase end.',
  steps: 'Step 2 begins after the combined building phase when a non-Trust network reaches step2CityThreshold; remove and replace the lowest current plant. The Step 3 card triggers removal of itself and the lowest current plant without replacement, shuffles the remaining deck, and activates Step 3 at resources if drawn during auctions or next round if drawn at settlement. If necessary Step 2 changes happen first. Step 3 appearing at settlement before Step 2 uses Step 2 refill values once.',
  mapRules: 'Germany: purchase of plant 39 permanently stops uranium refill. USA: consumed coal goes to separate coal storage; when the coal market is empty, stored coal can be bought at the map\'s specified price. That storage also supplies coal refill.',
  experiencedStart: 'When enabled, players mark distinct unoccupied starting cities anywhere in the selected playing zone during setup; multiple markers may share an area. Markers are shared, not owned by the chooser. A player without a network must claim an available marked city as their first city. Unclaimed marked cities cannot be connected by an existing network during Step 1.',
  trust: 'When enabled, the Trust is an automatic third faction. Its initial cities block other players during Step 1. It takes the highest current plant free, but with three plants only replaces its smallest with a higher plant. It takes one production\'s fuel free (hybrids alternate coal and oil starting with coal), returning resources at settlement without income. Connecting an empty city adds a free Trust house in the second slot while it has houses. It does not build on its own turn or compete for victory.',
} as const;
